<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,700,600' rel='stylesheet' type='text/css' />

<?php

$this->HeadLink ()->appendStylesheet ( '/css/jquery-ui.multidatespicker.css' );
$this->HeadLink ()->appendStylesheet ( '/css/animate.css' );
$this->HeadLink ()->appendStylesheet ( '/css/jquery-ui.css' );
$this->HeadLink ()->appendStylesheet ( '/css/style.css' );
$this->HeadLink ()->appendStylesheet ( '/css/default.css' );
$this->HeadLink ()->appendStylesheet ( '/css/main.css' );
$this->HeadLink ()->appendStylesheet ( '/css/icon.css' );

$this->HeadLink ()->appendStylesheet ( '/js/jqwidgets/styles/jqx.base.css' );
$this->HeadLink ()->appendStylesheet ( '/js/jqwidgets/styles/jqx.base-custom.css' );

$this->HeadLink ()->appendStylesheet ( '/css/uploadify.css' );
$this->HeadLink ()->appendStylesheet ( '/css/jsDatePick_ltr.min.css' );

$this->HeadLink ()->appendStylesheet ( '/css/jquery-ui-timepicker-addon.css' );
$this->HeadLink ()->appendStylesheet ( '/js/colorpicker/colpick.css' );
$this->HeadLink ()->appendStylesheet ( '/css/fullcalendar.print.css' );
$this->HeadLink ()->appendStylesheet ( '/css/fullcalendar.min.css' );
$this->HeadLink ()->appendStylesheet ( '/css/jquery.jscrollpane.css' );

echo $this->HeadLink ();