<div class="cmnSort">
  <div class="selectDrop">
    <select class="dropdown" id="<?php echo $prefixId; ?>selectGridView" name="selectGridView">
      <option value="">Select View</option>
      <?php foreach($gridViewOptions as $key => $data){ ?>
      <option value="<?php echo $data['id']; ?>"<?php if ($data['is_default']) { echo ' selected'; }?>><?php echo $data['view_title']; ?></option>
      <?php } ?>
    </select>
  </div>
  <a href="javascript:;" onclick="editMyGridView('<?php echo $prefixId; ?>');" id="<?php echo $prefixId; ?>editMyGridView" data-popup="<?php echo $prefixId; ?>myGridView" class="lightBoxClick">Edit</a> | <a href="javascript:;" onclick="deleteMyGridView('<?php echo $prefixId; ?>');">Delete</a> | <a href="javascript:;" onclick="$('#<?php echo $prefixId; ?>frm_mygridview')[0].reset(); $('#<?php echo $prefixId; ?>hiddenGenerateNewGridView').val(1); $('#<?php echo $prefixId; ?>frm_mygridview .errorText').remove();" class="lightBoxClick" data-popup="<?php echo $prefixId; ?>myGridView" id="<?php echo $prefixId; ?>addMyGridView">Create New View</a>
  <div class="mainSearch marR10">
    <input type="text" class="searchInput" placeholder="search.." id="<?php echo $prefixId; ?>searchInput">
    <input type="button" class="inputGo" value="Go!" id="globalGridSearch" onclick="searchGridsData('<?php echo $prefixId; ?>');">
  </div>
  <?php /*?><a href="javascript:;" onclick="searchInputClear('<?php echo $prefixId; ?>');">Clear</a><?php */?><span id="searchResultsHint" style="color:red;"></span></div>
<script type="text/javascript">
	searchByEnterKey('<?php echo $prefixId; ?>searchInput', 'globalGridSearch');
</script>
<script type="text/javascript">
$(document).ready(function(){
	$('#<?php echo $prefixId; ?>editMyGridView').removeClass('lightBoxClick');
	$('#<?php echo $prefixId; ?>editMyGridView').removeAttr('data-popup');
	$('#<?php echo $prefixId; ?>hiddenSelectGridView').val($('#<?php echo $prefixId; ?>selectGridView').val());
	searchGridsData('<?php echo $prefixId; ?>');
});


$('#<?php echo $prefixId; ?>selectGridView').dropkick({
	change: function () {
		$('#<?php echo $prefixId; ?>hiddenSelectGridView').val($('#<?php echo $prefixId; ?>selectGridView').val());
		searchGridsData('<?php echo $prefixId; ?>');
	}
});
</script>
