<div class="contentArea" id="oppGridContentArea">
	<h2 class="cmnHeader">Opportunities</h2>
	<!--BOF Grid View Header Block-->
	<?php echo $this->partial('customer/index/gridviewheader.phtml', array('gridViewOptions' => $this->gridViewOptions, 'recordsPerPage' => $this->recordsPerPage, 'prefixId' => 'opp_')); echo '<div class="pageLoader"></div>';  ?>
	<!--EOF Grid View Header Block-->

<div class="cb"></div>
<form name="frm_filter_fpportunity" id="frm_filter_fpportunity" action="" method="post">
	<div class="commonForm addOpportunitySearch">
		<div class="culmn">
			<div class="formRow">
				<label class="labelControll">Status</label>
				<div class="inputDiv">
					<div class="selectDrop">
						<select name="filter_status" id="filter_status" class="dropdown">
							<?php foreach($statusOptions as $value => $text) : ?>
								<option value="<?php echo $value; ?>"<?php if ($value == 'Open') echo " selected"; ?>><?php echo $text; ?></option>							
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</div>
		</div>
		<div class="culmn">
			<div class="formRow">
				<label class="labelControll">Owner</label>
        	  	<div class="inputDiv">
					<div class="selectDrop">
						<select name="filter_owner" id="filter_owner" class="dropdown">
							<?php foreach($ownerOptions as $value => $text) : ?>
								<option value="<?php echo $value; ?>"<?php if ($value == $loginUserId) echo " selected"; ?>><?php echo $text; ?></option>							
							<?php endforeach; ?>
						</select>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>

<div class="tableData tableNeView" style="overflow:visible">
    <div class="tableHading" style="width:100%" id="bindAfterThis"> Opportunity List </div>
    <div class="formTable manageMembers" id="jqxOpportunities">
    </div>
  </div>
</div>
<!--BOF Grid View Block-->
<?php echo $this->partial('customer/index/gridview.phtml', array('formType' => 'opportunities', 'recordsPerPage' => $this->recordsPerPage, 'columnList' => $this->columnList, 'hiddenUserId' => $this->loginUserId, 'prefixId' => 'opp_')); ?>
<!--EOF Grid View Block-->

<!--BOF Customer Mobile lookup list-->
<?php echo $this->partial('opportunities/index/customermobilelookup.phtml', array('recordsPerPage' => $this->recordsPerPage)); ?>
<!--EOF Customer Mobile lookup list-->

<!--BOF Customer lookup list-->
<?php echo $this->partial('opportunities/index/customerlookup.phtml', array('recordsPerPage' => $this->recordsPerPage, 'lookupCustomerId' => 'referred_by_customer', 'lookupCustomerName' => 'referred_by_name')); ?>
<!--EOF Customer lookup list-->

<!--BOF Edit Note Block-->
<?php echo $this->partial('opportunities/index/editnotes.phtml', array()); ?>
<!--EOF Edit Note Block-->