<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body>
<table  width="100%" cellpadding="15" cellspacing="0" border="0" style="width:700px; max-width:100%; border:#ccc solid 1px" align="center">
	<tr><td style="background-color:#323a45; padding:10px"><img src="<?php echo $this->serverUrl('/images/logo.jpg'); ?>"></td></tr>
	<tr><td style="font-family:'Calibri', Arial, sans-serif; font-size:11px; color:#333; padding:15px 15px; font-weight:700;">
	Hi <?php echo $msgholdename; ?>,
	</td></tr>
	<tr><td style="font-family:'Calibri', Arial, sans-serif; font-size:11px; color:#333; padding:15px 15px">
	<?php echo $data['message']; ?>
	</td></tr>
	<tr><td>		
		<table border="0" cellpadding="5" cellspacing="0" width="100%">
			<tr>
				<th align="left" style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333;font-weight:700; border-bottom:#333 solid 1px;">Item</th>
				<th align="left" style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333;font-weight:700; border-bottom:#333 solid 1px;">Description</th>
				<th style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333;font-weight:700; border-bottom:#333 solid 1px;" align="right">Quantity</th>
				<th style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333;font-weight:700; border-bottom:#333 solid 1px;" align="right">Unit Price</th>
				<th style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333;font-weight:700; border-bottom:#333 solid 1px;" align="right">Discount</th>
				<th style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333;font-weight:700; border-bottom:#333 solid 1px;" align="right">Amount USD</th>
			</tr>
			<?php foreach($data['items'] as $item){ ?>
			<tr>
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#ececec solid 1px;" valign="top" align="left"><?php echo ucfirst($item['item_type']); ?></td>
				<td align="left" width="33%" style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#ececec solid 1px;" valign="top"><?php echo $item['description']; ?></td>
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#ececec solid 1px;" valign="top" align="right"><?php echo $item['quantity']; ?></td>
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#ececec solid 1px;" valign="top" align="right"><?php echo $item['unit_price']; ?></td>
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#ececec solid 1px;" valign="top" align="right"><?php echo empty($item['discount']) ? '0.00' : $item['discount']; ?>%</td>
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#ececec solid 1px;" valign="top" align="right"><?php echo $item['amount']; ?></td>
			</tr>
			<?php } ?>							
			<tr>
				<td colspan="2">&nbsp;</td>
				<td colspan="2" style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#333 solid 1px;" valign="top" align="right"></td>
				
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#333 solid 1px;" valign="top" align="right">Subtotal</td>
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#333 solid 1px;" valign="top" align="right">150.00</td>
			</tr>
			<tr>
				<td colspan="2">&nbsp;</td>
				<td colspan="2" style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333; border-bottom:#333 solid 1px;" valign="top" align="right"></td>
				
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333;font-weight:700; border-bottom:#333 solid 1px;" valign="top" align="right">TOTAL USD</td>
				<td style="font-family:Helvetica,Arial,sans-serif;font-size:13px;color:#333;font-weight:700; border-bottom:#333 solid 1px;" valign="top" align="right">150.00</td>
			</tr>
		</table>		
	</td></tr>
	<tr>
		<td  style="font-family:'Calibri', Arial, sans-serif; font-size:11px; color:#817070; line-height:18px">
			Sincerly,<br />
			The Diamond Emporium Team<br />
			info@diamondemporium.com.au<br />
			<a href="https://www.diamondemporium.com.au/">https://www.diamondemporium.com.au/</a>
		</td>
	</tr>			  
	<tr>
		<td colspan="3" align="center" height="20">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="3" align="center" style="font-family:'Calibri', Arial, sans-serif; font-size:11px; color:#414042;">Copyright &copy; 2014 Diamond Emporium, All rights reserved.<br />PO Box A2034, Sydney South, NSW 1235, Australia</td>
	</tr>
</table>
</body>
</html>
