<div class="full robotoregular">
    <div class="full triple-padded">
    <div class="one-sisxth">
        <a href="javascript:;" class="btn btn-large btn-success"><i class="icon-newlead fs-28 top-8 relative"></i> New lead</a>
    </div>
    <div class="two-third align-center">
        <a href="javascript:;" class="btn btn-large "><i class="icon-lead fs-28 top-8 relative"></i> Leads</a>
        <a href="javascript:;" class="btn btn-large "><i class="icon-dashboard fs-28 top-8 relative"></i> Dashboard</a>
    </div>
    <div class="one-sisxth pull-right align-right lh-50">
        <label>September 1st - September 30th</label>
    </div>
</div>

<div class="full bg-white triple-pad-left triple-pad-right double-pad-top double-pad-bottom">
    <div class="pull-left">
        <label class="pull-left gap-right lh-28 color-gray5">Rings</label>
        <a href="javascript:;" class="btn">$2K - $5K</a>
        <a href="javascript:;" class="btn">$5K - $10K</a>
        <a href="javascript:;" class="btn">$11K - $20K</a>
        <a href="javascript:;" class="btn">$20K+</a>
        <a href="javascript:;" class="btn">Show all</a>

        <label class="gap-right lh-28 triple-gap-left color-gray5">Accessories</label>
        <a href="javascript:;" class="btn">Show all</a>
    </div>
    <div class="pull-right">
        <label class="pull-left double-gap-right lh-28 color-gray5 ">Filter by:</label>

        <ul class="dropdown dd-small bg-white d-i-b pull-left relative wd-60 triple-gap-right">
            <li>
                <a href="javascript:;" class="selected-text d-b users" value="All"><span class="d-i-b">Status </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>
            </li>
            <li>
                <ul class="dropdownOptions bg-white absolute wd-100" style="display:none;">
                    <li><a href="javascript:;" value="Option 1">Option 1</a></li>
                    <li><a href="javascript:;" value="Option 2">Option 2</a></li>
                    <li><a href="javascript:;" value="Option 3">Option 3</a></li>
                    <li><a href="javascript:;" value="Option 4">Option 4</a></li>
                    <li><a href="javascript:;" value="Option 5">Option 5</a></li>
                </ul>
            </li>
        </ul>

        <ul class="dropdown dd-small bg-white d-i-b pull-left relative wd-80 triple-gap-right">
            <li>
                <a href="javascript:;" class="selected-text d-b users" value="All"><span class="d-i-b">Referral </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>
            </li>
            <li>
                <ul class="dropdownOptions bg-white absolute wd-100" style="display:none;">
                    <li><a href="javascript:;" value="Option 1">Option 1</a></li>
                    <li><a href="javascript:;" value="Option 2">Option 2</a></li>
                    <li><a href="javascript:;" value="Option 3">Option 3</a></li>
                    <li><a href="javascript:;" value="Option 4">Option 4</a></li>
                    <li><a href="javascript:;" value="Option 5">Option 5</a></li>
                </ul>
            </li>
        </ul>

        <ul class="dropdown dd-small bg-white d-i-b pull-left relative wd-100">
            <li>
                <a href="javascript:;" class="selected-text d-b users" value="All"><span class="d-i-b">This month </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>
            </li>
            <li>
                <ul class="dropdownOptions bg-white absolute wd-100" style="display:none;">
                    <li><a href="javascript:;" value="Option 1">Option 1</a></li>
                    <li><a href="javascript:;" value="Option 2">Option 2</a></li>
                    <li><a href="javascript:;" value="Option 3">Option 3</a></li>
                    <li><a href="javascript:;" value="Option 4">Option 4</a></li>
                    <li><a href="javascript:;" value="Option 5">Option 5</a></li>
                </ul>
            </li>
        </ul>

    </div>
</div>

<div class="full triple-padded align-center">

<div class="one-fourth one-half-pad-left one-half-pad-right">
    <div class="full">
        <div class="full activelead">
            <img alt="Profile image" src="/images/temp/profimg.png">
            <label class="robotomedium fs-18 color-gray5 full gap-top">Natalie Fong</label>
        </div>
        <div class="full">
            <label class="display-inline-block border-count-white">3</label>
            <label class="display-inline-block border-count-green">3</label>
            <label class="display-inline-block border-count-red">2</label>
        </div>
        <div class="full triple-pad-left triple-pad-right triple-pad-top">
            <ul class="lead-list full lh-38">
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_walkIn.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic_facebook.png" /></li>
                <li class="bg-red1">Carita Navin <img alt="Profile image" src="/images/ic_wordMouth.png" /></li>
                <li class="bg-skip">Skipped <img alt="Profile image" src="/images/imgskip.png" /></li>
                <li class="bg-nextline">Next in line <img alt="Profile image" src="/images/ic_addplus.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic-google.png" /></li>
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_other.png" /></li>
                <li class="bg-red1">Carita Navin <img alt="Profile image" src="/images/ic_wordMouth.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic_facebook.png" /></li>                
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_pClient.png" /></li>
            </ul>
        </div>
    </div>
</div>

<div class="one-fourth one-half-pad-left one-half-pad-right">
    <div class="full">
        <div class="full">
            <img alt="Profile image" src="/images/temp/profimg.png">
            <label class="robotomedium fs-18 color-gray5 full gap-top">Natalie Fong</label>
        </div>
        <div class="full">
            <label class="display-inline-block border-count-white">3</label>
            <label class="display-inline-block border-count-green">3</label>
            <label class="display-inline-block border-count-red">2</label>
        </div>
        <div class="full triple-pad-left triple-pad-right triple-pad-top">
            <ul class="lead-list full lh-38">
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_walkIn.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic_facebook.png" /></li>
                <li class="bg-red1">Carita Navin <img alt="Profile image" src="/images/ic_wordMouth.png" /></li>
                <li class="bg-skip">Skipped <img alt="Profile image" src="/images/imgskip.png" /></li>
                <li class="bg-nextline">Next in line <img alt="Profile image" src="/images/ic_addplus.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic-google.png" /></li>
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_other.png" /></li>
                <li class="bg-red1">Carita Navin <img alt="Profile image" src="/images/ic_wordMouth.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic_facebook.png" /></li>                
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_pClient.png" /></li>
            </ul>
        </div>
    </div>
</div>
<div class="one-fourth one-half-pad-left one-half-pad-right">
    <div class="full">
        <div class="full">
            <img alt="Profile image" src="/images/temp/profimg.png">
            <label class="robotomedium fs-18 color-gray5 full gap-top">Natalie Fong</label>
        </div>
        <div class="full">
            <label class="display-inline-block border-count-white">3</label>
            <label class="display-inline-block border-count-green">3</label>
            <label class="display-inline-block border-count-red">2</label>
        </div>
        <div class="full triple-pad-left triple-pad-right triple-pad-top">
            <ul class="lead-list full lh-38">
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_walkIn.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic_facebook.png" /></li>
                <li class="bg-red1">Carita Navin <img alt="Profile image" src="/images/ic_wordMouth.png" /></li>
                <li class="bg-skip">Skipped <img alt="Profile image" src="/images/imgskip.png" /></li>
                <li class="bg-nextline">Next in line <img alt="Profile image" src="/images/ic_addplus.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic-google.png" /></li>
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_other.png" /></li>
                <li class="bg-red1">Carita Navin <img alt="Profile image" src="/images/ic_wordMouth.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic_facebook.png" /></li>                
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_pClient.png" /></li>
            </ul>
        </div>
    </div>
</div>
<div class="one-fourth one-half-pad-left one-half-pad-right">
    <div class="full">
        <div class="full">
            <img alt="Profile image" src="/images/temp/profimg.png">
            <label class="robotomedium fs-18 color-gray5 full gap-top">Natalie Fong</label>
        </div>
        <div class="full">
            <label class="display-inline-block border-count-white">3</label>
            <label class="display-inline-block border-count-green">3</label>
            <label class="display-inline-block border-count-red">2</label>
        </div>
        <div class="full triple-pad-left triple-pad-right triple-pad-top">
            <ul class="lead-list full lh-38">
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_walkIn.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic_facebook.png" /></li>
                <li class="bg-red1">Carita Navin <img alt="Profile image" src="/images/ic_wordMouth.png" /></li>
                <li class="bg-skip">Skipped <img alt="Profile image" src="/images/imgskip.png" /></li>
                <li class="bg-nextline">Next in line <img alt="Profile image" src="/images/ic_addplus.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic-google.png" /></li>
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_other.png" /></li>
                <li class="bg-red1">Carita Navin <img alt="Profile image" src="/images/ic_wordMouth.png" /></li>
                <li class="bg-green1">Carita Navin <img alt="Profile image" src="/images/ic_facebook.png" /></li>                
                <li class="bg-white">Carita Navin <img alt="Profile image" src="/images/ic_pClient.png" /></li>
            </ul>
        </div>
    </div>
</div>

</div>
</div>
<?php 
foreach ($data as $URL) {
    ?>
    <tr>
        <td><?php 
        //echo $URL['first_name'];
        ?></td>
        
    <tr>
<?php } ?>
   
  