<form name="frm_chain" id="frm_chain" method="post" enctype="multipart/form-data" action="/uploadfile">
  <div class="contentArea padLR0">
    <div class="pageLoader"></div>
    <div class="fl width100p contentINN">
      <div class="customerDetails">
        <label>Supplier Details</label>
        <div class="custonerInfo">
          <h2><?php echo $viewData['company_name']; ?></h2>
          <p>Ph: <?php echo $viewData['supplier_phone']; ?></p>
          <p>E: <a href="mailto:<?php echo $viewData['supplier_email']; ?>"><?php echo $viewData['supplier_email']; ?></a></p>
        </div>
      </div>
      <span class="deviderLine" ></span> </div>
    <div class="customerTabing fl width100p ctb">
      <ul>
        <li class="current"><a href="javascript:;">Chain Details</a></li>
      </ul>
      <div class="customTabbingInner">
        <!-- Lead Details -->
        <div class="customerTabingInfo" style="display:block">
          <div class="leadSummary QuoteMain">
          <a class="cmnBtn" id="saveChainButton" href="javascript:;" onclick="updateChain($('#frm_chain'));">Edit</a> &nbsp;
          <?php if ($canDelete) : ?>
          	<a class="cmnBtn redBtn" href="javascript:;" onclick="deleteChain(<?php echo $viewData['id']; ?>);">Delete</a> &nbsp;
          <?php endif; ?>
            <!-- Lead Information-->
            <div class="tableData noOverflow width100p">
				<input id="chainRingId" type="hidden" value="<?php echo $viewData['id']; ?>" name="chainRingId">
				<input id="supplier_id" type="hidden" value="<?php echo $viewData['supplier_id']; ?>" name="supplier_id">
				<input id="invoice" type="hidden" value="<?php echo $viewData['image']; ?>" name="image">
				<input id="invoice" type="hidden" value="<?php echo $viewData['invoice']; ?>" name="invoice">
              <div  class="tableHading width100p"> Chain Details <?php echo '- #'.$viewData['stock_code']; ?></div>
              <div class="fl width100p commonForm rowSpace suplierInfo editViewForm">
			  <div class="alphaClmn">
                  <div class="formRow">
                    <label class="labelControll">Style</label>
                    <div class="inputDiv displayHide">
                      <select class="dropdown" id="style" name="style">
                        <?php foreach($this->fetchChainStyleOptions as $id => $title){?>
                        <option value="<?php echo $id; ?>" <?php if($viewData['style'] == $title){?> selected="selected" <?php } ?>><?php echo $title; ?></option>
                        <?php } ?>
                      </select>
                    </div>
                    <p class="hiddenUnqValues" id="style_chain">
                      <?php 
					  echo $viewData['style']; ?>
                    </p>
                  </div>
				  <div class="formRow" id="other_style_div" style="display:none">
                    <label class="labelControll"></label>
                    <div class="inputDiv displayHide">
                      <input type="text" name="other_style" id="other_style" value="<?php echo $viewData['other_style']; ?>" class="inputTxt" maxlength="64"/>
                    </div>
                    <p class="hiddenUnqValues" id="other_style_chain">
                      <?php echo $viewData['other_style']; ?>
                    </p>
                  </div>
				  <div class="formRow">
                    <label class="labelControll">Length</label>
                    <div class="inputDiv displayHide">
                      <?php /*?><input type="text" class="inputTxt" id="length" name="length" value="<?php echo $viewData['length']; ?>" data-numeric="yes" /><?php */?>
					 
					  <select class="dropdown" id="length" name="length">
					  	<option value="0">Select</option>
                        <?php for($i=35;$i<=70;$i++){ ?>
                        <option value="<?php echo $i; ?>" <?php if($viewData['length'] == $i){?> selected="selected" <?php } ?>><?php echo $i; ?></option>
                        <?php } ?>
                      </select>
                    </div>
                    <p class="hiddenUnqValues" id="length_chain">
                      <?php 
					  echo $viewData['length']; ?>
                    </p>
                  </div>
				  <div class="formRow">
                    <label class="labelControll">Thickness</label>
                    <div class="inputDiv displayHide">
                      <input type="text" class="inputTxt" id="thickness" name="thickness" value="<?php echo $viewData['thickness']; ?>" data-numeric="yes" />
                    </div>
                    <p class="hiddenUnqValues" id="thickness_chain">
                      <?php 
					  echo $viewData['thickness']; ?>
                    </p>
                  </div>
				  <div class="formRow">
                    <label class="labelControll">Metal Type</label>
                    <div class="inputDiv displayHide">
                      <select class="dropdown" id="metal_type" name="metal_type">
                        <?php foreach($this->metalTypesLookup as $id => $title){?>
                        <option value="<?php echo $id; ?>" <?php if($viewData['metal_type'] == $title){?> selected="selected" <?php } ?>><?php echo $title; ?></option>
                        <?php } ?>
                      </select>
                    </div>
                    <p class="hiddenUnqValues" id="metal_type_chain">
                      <?php 
					  echo $viewData['metal_type']; ?>
                    </p>
                  </div>
				  <div class="formRow">
                    <label class="labelControll">Metal Weight</label>
                    <div class="inputDiv displayHide">
                      <input type="text" class="inputTxt" id="metal_weight" name="metal_weight" value="<?php echo $viewData['metal_weight']; ?>" data-numeric="yes" />
                    </div>
                    <p class="hiddenUnqValues" id="thickness_chain">
                      <?php 
					  echo $viewData['metal_weight']; ?>
                    </p>
                  </div>
				  </div>
				  <div class="betaClmn">
				  	<div class="formRow">
                    <label class="labelControll">Description</label>
                    <div class="inputDiv displayHide">
                      <textarea id="description" name="description" style="height:100px"><?php echo $viewData['description']; ?></textarea>
                    </div>
                    <p class="hiddenUnqValues" id="description_chain">
                      <?php 
					  echo $viewData['description']; ?>
                    </p>
                  </div>
                  <div class="formRow">
                    <label class="labelControll">Upload Image</label>
                    <div class="inputDiv displayHide">
                      <div class="inputfile"><span class="cmnBtn blueBtn marL0">Upload</span>
                        <input type="file" name="item_image" id="item_image" />
                      </div>
                      <div class="uploadedImgDisplay" id="preview"></div>
                    </div>
					<p class="hiddenUnqValues" id="image_chain">
					<?php if($viewData['image'] != ''){ ?>
                      <img src="/inventory_images/<?php echo $viewData['image']; ?>"  style="max-width:100%; max-height:200px" >
					  <?php } ?>
                    </p>
                  </div>
				  </div>
				<div class="headSettings">
          <h2 class="cmnHeader">Supplier & Invoices</h2>
          <div class="alphaClmn">
            <div class="formRow">
              <label class="labelControll">Attach Invoice</label>
              <div class="inputDiv displayHide">
                <div class="inputfile"><span class="cmnBtn blueBtn marL0">Upload</span>
                  <input type="file" id="item_invoice" name="item_invoice">
                </div>
				<div class="uploadedInvoiceDisplay" id="invoicePreview"></div>
              </div>
			  <p class="hiddenUnqValues" id="invoice_diamond">
				<a href="/invoice/<?php echo $viewData['invoice']; ?>" id="invoice_link" target="_blank" <?php if(empty($viewData['invoice'])) echo 'style="display:none;"' ?>>Invoice</a>
              </p>
            </div>
            <div class="formRow">
              <label class="labelControll">Supplier Name</label>
              <div class="inputDiv displayHide"><input type="text" value="<?php echo $viewData['supplier_name']; ?>" class="inputTxt width60p" id="supplier_name" name="supplier_name" readonly="readonly"><a onclick="suppliersLookup(<?php echo $this->recordsPerPage; ?>, 'supplier_id', 'supplier_name');" data-popup="supplierlookup" class="cmnBtn blueBtn lightBoxClick" href="javascript:;">Lookup</a></div>
			  <p class="hiddenUnqValues" id="supplier_name_chain">
                      <?php 
					  echo $viewData['supplier_name']; ?>
                    </p>
            </div>
          </div>
          <div class="betaClmn">
            <div class="formRow">
              <label class="labelControll">Price</label>
              <div class="inputDiv displayHide"><input type="text" value="<?php echo $viewData['price']; ?>" class="inputTxt" id="price" name="price" data-numeric="yes" /></div>
			   <p class="hiddenUnqValues" id="price_chain">
                     <?php if($viewData['price'] > 0){ echo '$'.$viewData['price']; }?>
                    </p>
            </div>
          </div>
        </div>
              </div>
            </div>
            <div class="tableData noOverflow width100p">
              <div  class="tableHading width100p"> Consignment <a href="javascript:;" data-popup="consignItem" class="cmnBtn fr marT0 lightBoxClick" onclick="openConsignForm(<?php echo $viewData['id']; ?>, 'chain', 'edit');">Consign</a></div>
              <div class="fl width100p  suplierInfo">
                <div class="commonForm rowSpace addItemForm consignPopup consignPopupView">
                  <div class="headSettings padT0">
                    <h2 class="cmnHeader">Inventory Status</h2>
                    <div class="alphaClmn">
                      <div class="formRow">
                        <label class="labelControll">Inventory Status</label>
                        <p class="inputDiv" id="inventory_status_name_weddring"><?php echo $this->ConsignData['inventory_status_name']; ?></p>
                      </div>
                      <div class="formRow">
                        <label class="labelControll">Status Reason</label>
                        <div class="inputDiv" id="inventory_status_reason_weddring"><?php echo $this->ConsignData['inventory_status_reason']; ?></div>
                      </div>
                    </div>
                    <div class="betaClmn">
                      <div class="formRow">
                        <label class="labelControll">Inventory Type</label>
                        <div class="inputDiv" id="inventory_type_weddring"><?php echo $this->ConsignData['inventory_type']; ?></div>
                      </div>
                      <div class="formRow">
                        <label class="labelControll">Consignee Owner</label>
                        <div class="inputDiv" id="owner_name_weddring"><?php echo $this->ConsignData['owner_name']; ?></div>
                      </div>
                    </div>
                  </div>
                  <div class="headSettings">
                    <h2 class="cmnHeader">Inventory Reservation</h2>
                    <div class="alphaClmn">
                      <div class="formRow">
                        <label class="labelControll">Reserve Time</label>
                        <div class="inputDiv" id="reserve_time_weddring"><?php echo $this->ConsignData['reserve_time']; ?></div>
                      </div>
                    </div>
                    <div class="betaClmn">
                      <div class="formRow">
                        <label class="labelControll">Reserve Notes</label>
                        <div class="inputDiv" id="reserve_notes_weddring"><?php echo $this->ConsignData['reserve_notes']; ?></div>
                      </div>
                    </div>
                  </div>
                  <div class="headSettings">
                    <h2 class="cmnHeader">Item Location</h2>
                    <div class="alphaClmn">
                      <div class="formRow">
                        <label class="labelControll">Tracking Status</label>
                        <div class="inputDiv" id="inventory_tracking_status_weddring"><?php echo $this->ConsignData['inventory_tracking_status']; ?></div>
                      </div>
                      <div class="formRow">
                        <label class="labelControll">Tracking Reason</label>
                        <div class="inputDiv" id="inventory_tracking_reason_weddring"><?php echo $this->ConsignData['inventory_tracking_reason']; ?></div>
                      </div>
                    </div>
                    <div class="betaClmn">
                      <div class="formRow">
                        <label class="labelControll">Tracking ID</label>
                        <div class="inputDiv" id="tracking_id_weddring"><?php echo $this->ConsignData['tracking_id']; ?></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<!--BOF Supplier lookup list-->
<?php echo $this->partial('inventory/index/supplierlookup.phtml', array('recordsPerPage' => $this->recordsPerPage, 'lookupSupplierId' => 'supplier_id', 'lookupSupplierName' => 'supplier_name')); ?>
<!--EOF Supplier lookup list-->
<!--BOF Add Consign Form -->
<div class="lightBox" id="consignItem">
	<div class="lightBoxMid" style="width:890px">
		<div class="lightBoxTitle">Consign Item	  -  Chain <a href="javascript:;" class="closePopup" title="Close">X</a></div>
		<div class="lightBoxContent fl width100p" id="consign_form_content">
		</div>
	</div>
</div>
<!--EOF Add Consign Form -->
<script type="text/javascript">
searchByEnterKey('lookupsrc', 'supplierLookupSearch');
$(document).ready(function() {
	
	<?php if($viewData['image'] != ''){ ?>
	$('#preview').html('<img src="/inventory_images/<?php echo $viewData['image']; ?>" >');
	<?php } ?>
	$('#item_image').live('change', function(){ 
		$("#preview").html('');
		//$("#preview").html('<img src="loader.gif" alt="Uploading...."/>');
		$("#frm_chain").ajaxForm({
			//target: '#preview',
			success: function(response){
				$('#image').val(response);
				$('#item_image').val('');
				$('#preview').html('<img src="/inventory_images/'+response+'" >');
			}
		}).submit();
	});
	
	$('#item_invoice').live('change', function(){ 
		//$("#preview").html('<img src="loader.gif" alt="Uploading...."/>');
		$("#frm_chain").ajaxForm({
			success: function(response){
				if(response){
					$('#invoicePreview').html(response);
					$('#invoice').val(response);
					$('#invoice_link').attr('href', '/invoice/'+response);
					$('#invoice_link').show();
					$('#item_invoice').val('');
				}
			}
		}).submit();
	});
	
	var SelectedValue = $("#style option[value="+$('#style option:selected').val()+"]").text();
	if(SelectedValue == "Other"){
		$('#other_style_div').show();
	} else {
		$('#other_style').val('');
		$('#other_style_div').hide();
	}
	$('#style').dropkick({
		change: function () {
			var SelectedValue = $("#style option[value="+$('#style option:selected').val()+"]").text();
			if(SelectedValue == "Other"){
				$('#other_style').val('');
				$('#other_style_div').show();
			} else {
				$('#other_style').val('');
				$('#other_style_chain').text('');
				$('#other_style_div').hide();
			}
		}
	});
});
</script>
