<!-- Add tem Light Box -->
<div class="lightBox" id="addItem">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Add Chain<a href="javascript:;" class="closePopup" onclick="closeButtonProperty('frm_chain');" title="Close">X</a></div>
    <div class="lightBoxContent fl width100p">
      <?php
		$inventoryForm->prepare();
		echo $this->form()->openTag($inventoryForm);
		echo $this->formElement($this->inventoryForm->get('supplier_id'));
		echo $this->formElement($this->inventoryForm->get('image'));
		echo $this->formElement($this->inventoryForm->get('invoice'));
	?>
      <div class="commonForm rowSpace addItemForm">
        <div class="alphaClmn">
          <div class="formRow">
            <label class="labelControll"><?php echo $this->inventoryForm->get('style')->getLabel(); ?></label>
            <div class="inputDiv">
              <div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('style')); ?></div>
            </div>
          </div>
          <div class="formRow" style="display:none;" id="other_style_div">
            <label class="labelControll"></label>
            <div class="inputDiv">
              <div class="selectDrop width100p">
                <input type="text" id="other_style" name="other_style" maxlength="64" class="inputTxt"/>
              </div>
            </div>
          </div>
          <div class="formRow">
            <label class="labelControll"><?php echo $this->inventoryForm->get('length')->getLabel(); ?></label>
            <div class="inputDiv">
              <div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('length')); ?></div>
            </div>
          </div>
          <div class="formRow">
            <label class="labelControll"><?php echo $this->inventoryForm->get('thickness')->getLabel(); ?></label>
            <div class="inputDiv">
              <div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('thickness')); ?></div>
            </div>
          </div>
          <div class="formRow">
            <label class="labelControll"><?php echo $this->inventoryForm->get('metal_type')->getLabel(); ?></label>
            <div class="inputDiv">
              <div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('metal_type')); ?></div>
            </div>
          </div>
          <div class="formRow">
            <label class="labelControll"><?php echo $this->inventoryForm->get('metal_weight')->getLabel(); ?></label>
            <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('metal_weight')); ?></div>
          </div>
        </div>
        <div class="betaClmn">
          <div class="formRow">
            <label class="labelControll"><?php echo $this->inventoryForm->get('description')->getLabel(); ?></label>
            <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('description')); ?></div>
          </div>
          <div class="formRow">
            <label class="labelControll">Upload Image</label>
            <div class="inputDiv">
              <div class="inputfile"><span class="cmnBtn blueBtn marL0">Upload</span>
                <input type="file" name="item_image" id="item_image" />
              </div>
              <div class="uploadedImgDisplay" id="preview"></div>
            </div>
          </div>
        </div>
        <div class="headSettings">
          <h2 class="cmnHeader">Supplier & Invoices</h2>
          <div class="alphaClmn">
            <div class="formRow">
              <label class="labelControll">Attach Invoice</label>
              <div class="inputDiv">
                <div class="inputfile"><span class="cmnBtn blueBtn marL0">Upload</span>
                  <input type="file" name="item_invoice" id="item_invoice" />
                </div>
				<div class="uploadedInvoiceDisplay" id="invoicePreview"></div>
              </div>
            </div>
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('supplier_name')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('supplier_name')); ?><a href="javascript:;" class="cmnBtn blueBtn lightBoxClick" data-popup="supplierlookup" onclick="suppliersLookup(20, 'supplier_id', 'supplier_name');">Lookup</a></div>
            </div>
          </div>
          <div class="betaClmn">
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('price')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('price')); ?></div>
            </div>
          </div>
        </div>
        <div class="formButtons tc fl width100p marB30"> <?php echo $this->formElement($this->inventoryForm->get('save')); ?> <?php echo $this->formElement($this->inventoryForm->get('cancel')); ?> </div>
      </div>
      <?php echo $this->form()->closeTag(); ?> </div>
  </div>
</div>
<!-- Add tem Light Box End-->
<!--BOF Supplier lookup list-->
<div class="lightBox" id="supplierlookup">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Supplier Lookup <a href="javascript:;" class="closePopup" title="Close">X</a></div>
    <div class="lightBoxContent fl width100p lookupPopup padB105">
      <div class="mainSearch">
        <input name="lookupsrc" id="lookupsrc" type="text" class="searchInput" placeholder="Search..">
        <input type="button" class="inputGo" value="Go!" onclick="suppliersLookup(20, 'supplier_id', 'supplier_name', $('#lookupsrc').val());" id="supplierLookupSearch">
        <!--<span id="searchResultsHintjqxCustomers" style="color:red;"></span>-->
      </div>
      <div class="tableData tableNeView" style="overflow:visible">
        <div class="tableHading"> Supplier List </div>
        <div class="formTable manageMembers" id="jqxSuppliersLookup" style="width:100%"> </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">

searchByEnterKey('lookupsrc', 'supplierLookupSearch');
<!--EOF Supplier lookup list-->
$(document).ready(function() {
	$('#item_image').live('change', function(){ 
		$("#preview").html('');
		//$("#preview").html('<img src="loader.gif" alt="Uploading...."/>');
		$("#frm_chain").ajaxForm({
			//target: '#preview',
			success: function(response){
				$('#image').val(response);
				$('#item_image').val('');
				$('#preview').html('<img src="/inventory_images/'+response+'" height="98px" width="234px">');
			}
		}).submit();
	});
	
	$('#item_invoice').live('change', function(){ 
		//$("#preview").html('<img src="loader.gif" alt="Uploading...."/>');
		$("#frm_chain").ajaxForm({
			success: function(response){
				$('#invoice').val(response);
				$('#invoicePreview').html(response);
				$('#item_invoice').val('');
			}
		}).submit();
	});
	
	$('#style').dropkick({
		change: function () {
			var SelectedValue = $("#style option[value="+$('#style option:selected').val()+"]").text();
			if(SelectedValue == "Other"){
				$('#other_style_div').show();
				$('#other_style').val('');
			} else {
				$('#other_style').val('');
				$('#other_style_div').hide();
			}
		}
	});
});
</script>
