<div class="contentArea">
  <h2 class="cmnHeader">Customers</h2>
  <a href="javascript:;" class="popupLink lightBoxClick" data-popup="new_customer_form">New Customer</a>
  <!--BOF Grid View Header Block-->
	<?php echo $this->partial('customer/index/gridviewheader.phtml', array('gridViewOptions' => $this->gridViewOptions, 'recordsPerPage' => $this->recordsPerPage, 'prefixId' => 'cus_')); ?>
  <!--EOF Grid View Header Block-->
  <div class="tableData tableNeView marB30" style="overflow:visible">
    <div class="tableHading" style="width:100%" id="bindAfterThis"> Customer List </div>
    <div class="formTable manageMembers" id="jqxCustomers" style="width:100%">
      
    </div>
    
  </div>
  <!--BOF Grid View Block-->
</div>
<?php echo $this->partial('customer/index/gridview.phtml', array('formType' => 'customers', 'recordsPerPage' => $this->recordsPerPage, 'columnList' => $this->columnList, 'hiddenUserId' => $this->loginUserId, 'prefixId' => 'cus_')); ?>
<!--EOF Grid View Block-->
<!--BOF new lead Form-->
<?php echo $this->partial('customer/index/newcustomerform.phtml', array('form' => $this->form, 'identity' => $this->identity, 'recordsPerPage' => $this->recordsPerPage)); ?>
<!--EOF new lead Form-->

<!--BOF Customer lookup list-->
<?php echo $this->partial('customer/leads/customerlookup.phtml', array('recordsPerPage' => $this->recordsPerPage, 'lookupCustomerId' => 'partner_id', 'lookupCustomerName' => 'partner_name')); ?>
<!--EOF Customer lookup list-->

<!--EOF Grid View Block-->
