<?php
/**
 * Created by PhpStorm.
 * User: Quan Lee
 * Date: 12/7/16
 * Time: 10:53 AM
 */

use Zend\Form\Element;
use Zend\Form\Form;
use Dashboard\Form\DashboardForm;


$form->prepare();

//Select Product
$selectproduct = array(
    array("Engagement Ring","ER"),
    array("Wedding Band","WB"),
    array("Eternity Band","EB"),
    array("Loose Diamond","LD"),
    array("Earrings","E"),
    array("Dress Rings","DR"),
    array("Pendant","P"),
    array("Bracelet","B"),
    array("Timepiece","T"),
    array("Custom Jewellery","CW"),
    array("Loose Gemstone","LG"),
    array("Other","O")
 );
$attrproduct = array(   
    'class' => 'dropdownOptions bg-white absolute full-width',
   
);
//Select Referral
$selectreferral = array(
    array("Google","/images/ic-google.png"),
    array("Word of mouth","/images/ic_wordMouth.png",),
    array("Previous client","/images/ic_pClient.png",),
    array("Walk In","/images/ic_walkIn.png",),
    array("Facebook","/images/ic_facebook.png",),
    array("Instagram","/images/ic_insta.png",),
    array("Other","/images/ic_other.png")
 );
// Assign To

$selectAssignTo = array(
    array("Shelley Bedarov","/images/customerPhoto.jpg","nextInline"),
    array("Natalie Fong","/images/customerPhoto.jpg",""),
    array("Bec O’brien","/images/customerPhoto.jpg",""),
    array("Aaron Langford","/images/customerPhoto.jpg",""),
 );
//Select Budget
$selectbudget = array(
    '$2,000 - $4,999',
    '$5,000 - $9,999',
    '$10,000 - $19,999',
    '$20,000 - $34,999',
    '$35,000 - $49,999',
    '$50,000 - $74,999',
    '$75,000 - $99,999',
    '$100,000+',
 );

//SElect Reference Product
$selectreferenceproduct = array(
    'Reference Product',
    'Reference Product',
    'Reference Product',
    'Reference Product',
    'Reference Product'
 );
//Select Communication Method
$communicationmethod = array(
    'Web Phone',
    'Phone',
    'Direct Email',
    'Live Chat',
    'Walk In',
    'Facebook',
    'Instagram'
 );
//Select Contact Method
$selectcontactmethod = array(
    'Phone/Email',
    'Phone',
    'Email',
    'Other'
 );

//Select Title Method
$selectTitle = array(
    'Unknown',
    'Mr',
    'Ms',
    'Mrs',
    'Miss'
 );

//Select Gender Method
$selectGender = array(
    'Male',
    'Female',
    'Other/Not Specified'
 );

//
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id')).'<div class="full basicInfo formfields color-darkGray initialScreen fs-14 hideOnSavenBook">';
    
   // -----------------------------------------------------------------
   // -----------------------------------------------------------------
   // Title Select

echo '<div class="relative pull-left gap-right pad-right">';
   echo '<div class="relative pull-left">';
    echo '<span style="display: none" class="text-top">*Title</span>';
        echo '<ul class="dropdown bg-white d-i-b pull-left relative title">';
             echo '<li>';
             echo '   <a href="javascript:;" class="selected-text d-b" value="All"><span id ="title" class="d-i-b">*Title</span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
             echo '</li>';
             echo '<li>';
             // echo $this->formRow($title);
                 echo    '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                        
                        foreach($selectTitle as $title){ 
                            echo '<li>';
                                echo "<a href='javascript:;' value='$title'> $title </a>";
                            echo '</li>';
                        }
                echo    '</ul>';

             echo '</li>';
        echo '</ul>';
        echo '<label class="opacity0 titleError">Please select title</label>';
    echo '</div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------
    // Gender Select
    echo '<div class="relative pull-left">';
    echo '<span style="display: none" class="text-top">*Gender</span>';
        echo '<ul class="dropdown bg-white d-i-b pull-left relative Gender">';
             echo '<li>';
             echo '   <a href="javascript:;" class="selected-text d-b" value="All"><span id ="Gender" class="d-i-b">*Gender</span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
             echo '</li>';
             echo '<li>';
             // echo $this->formRow($title);
                 echo    '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                        
                        foreach($selectGender as $Gender){ 
                            echo '<li>';
                                echo "<a href='javascript:;' value='$Gender'> $Gender </a>";
                            echo '</li>';
                        }
                echo    '</ul>';

             echo '</li>';
        echo '</ul>';
        echo '<label class="opacity0 genderError">Please select gender</label>';
    echo '</div>';
    echo '</div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // FirstName
    echo '<div class="relative pull-left"><span style="display: none">*First name</span>'.$this->formRow($form->get("first_name")).'<label class="opacity0 firstError">Only "-" and alphabets are allowed</label><label class="opacity0 requiredError">Please select first name</label></div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // LastName
    echo '<div class="relative pull-left"><span style="display: none">*Last name</span>'.$this->formRow($form->get("last_name")).'<label class="opacity0 firstError">Only "-" and alphabets are allowed</label><label class="opacity0 requiredError">Please select last name</label></div>';
    
    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // Phone
    echo '<div class="relative pull-left"><span style="display: none">*Phone number*</span>'.$this->formRow($form->get("phone_number")).'<label class="opacity0 firstError">Please enter a valid phone number</label><label class="opacity0 requiredError">Please select phone number</label></div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // email
    echo '<div class="relative pull-left emailDiv"><span style="display: none" class="text-top">*Email</span>'.$this->formRow($form->get("email")).'<label class="opacity0 error emailexists">Record not found</label><label class="opacity0 error ">Please enter a valid email</label><a href="javascript:;" class="availability absolute"><img class="redCross hide" src="/images/redCross.png")/><img class="redGreen hide" src="/images/greenTick.png"/></a><label class="opacity0 requiredError">Please select email</label></div>';

    // Assignee Name
    //echo '<div class="selectedAgent relative pull-left" di>
    //        <span style="display: none">Assigned to</span>
    //        <p class="userDp pull-left half-gap-top"></p>
    //        <p class="userName pull-left double-gap-top gap-left two-pad-left half-pad-top"></p>

    //    </div>'; 
   
    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    
    // Country List
    //echo '<div class="relative full pull-left initialScreen hideshow one-half-pad-top">';
    echo '<div class="relative full pull-left initialScreen  one-half-pad-top">';
    echo '<div id="countryName" class="hide" value="Australia"></div>
          
         <div class="relative pull-left countryDiv">
            <span style="display: inline-block" class="text-top">*Country </span>
            <i class="icon-dropdown fs-7 pull-right d-i-b "></i>
            <div class="ui-widget">
                <select id="combobox">

                </select>
            </div>
        </div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // States    
    
    echo '<div class="relative pull-left stateDiv">
        <span style="display: none" class="text-top">*State </span>
        <ul class="dropdown bg-white d-i-b pull-left relative wd-280 State">
            <li>
                <a href="javascript:;" class="selected-text d-b" value="All"><span id="stateDropdown" class="d-i-b">*State </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>
            </li>
            <li>
                <ul class="dropdownOptions bg-white absolute full-width" style="display:none;">
                        <li><a href="javascript:;" value="ACT">ACT</a></li>
                        <li><a href="javascript:;" value="NSW">NSW</a></li>
                        <li><a href="javascript:;" value="NT">NT</a></li>
                        <li><a href="javascript:;" value="QLD">QLD</a></li>
                        <li><a href="javascript:;" value="WA">WA</a></li>
                        <li><a href="javascript:;" value="TAS">TAS</a></li>
                        <li><a href="javascript:;" value="VIC">VIC</a></li>
                        <li><a href="javascript:;" value="SA">SA</a></li>
                </ul>
            </li>
        </ul>
        <label class="opacity0 error stateerror"> Please select State </label>
    </div> <!-- State Div End -->';  

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // Full Address 

    echo '<div class="relative pull-left"><span style="display: none" class="text-top">Full Address</span><input maxlength="90" autocomplete="Off" type="text" id="fullAddress" placeholder="Full Address (optional)" /></div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------
    
    
    //Communication Method
    
    echo '<div class="relative pull-left">';
      echo '<span style="display: none" class="text-top">Lead Source </span>';
      echo '<ul class="dropdown bg-white d-i-b pull-left relative wd-280 CommunicationMethod">';
            echo '<li>';
             echo '   <a href="javascript:;" class="selected-text d-b" value="All"><span id ="CommunicationMethod" class="d-i-b">Lead Source</span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
            echo '</li>';
            echo '<li>';
             // echo $this->formRow($title);
            echo    '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                        
                        foreach($communicationmethod as $method){ 
                            echo '<li>';
                                echo "<a href='javascript:;' value='$method'> $method </a>";
                            echo '</li>';
                        }
            echo    '</ul>';

            echo '</li>';
        echo '</ul>';

    echo '</div>';
    
    // -----------------------------------------------------------------
    // ----------------------------------------------------------------- 

    //ContactMethod

    echo '<div class="relative pull-left">';
      echo '<span style="display: none" class="text-top">Preferred method of contact </span>';
      echo '<ul class="dropdown bg-white d-i-b pull-left relative wd-280 preferredMethod">';
                echo '<li>';
                 echo '   <a href="javascript:;" class="selected-text d-b users" value="All"><span id="perferrefDropdown" class="d-i-b">Preferred method of contact </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
                echo '</li>';
                echo '<li>';
                 // echo $this->formRow($title);
                echo    '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                            
                            foreach($selectcontactmethod as $method){ 
                                echo '<li>';
                                    echo "<a href='javascript:;' value='$method'> $method </a>";
                                echo '</li>';
                            }
                echo    '</ul>';

                echo '</li>';
            echo '</ul>';
        echo '</div>';

       echo '</div>'; 

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

   //ContactMethod
    echo '<div class="relative pull-left hide one-half-gap-top"><span style="display: none" class="text-top">Preferred method of contact (Other)</span><input maxlength="45" autocomplete="Off" type="text" id="perferrefDropdownOther" placeholder="Preferred method of contact (Other)" /></div>';
       
    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // Add Address Fields 
    //echo $this->partial('dashboard/dashboard/addAddress.phtml');


        echo '<div class="add-address full double-gap-top half-pad-top" style="display: none;">';

           $image = '/images/ic_add.png';
           echo  '<a href="javascript:;" class="add-addressClick pull-left">';
           echo     "<img class='pull-left' src='$image' />";
           echo     '<p class="pull-left pad-left fs-14 color-blue pointer">Add address</p>';
           echo  '</a> <!-- add-address anchor End -->';

      echo '</div> <!-- next-screenDiv Div End -->';
      // Address section

echo '</div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

//Additional Detail
//Product
echo '<div class="additional-details full fs-14 pad-top hideOnSavenBook">';

echo '<h2 class="fs-24 color-green robotolight double-pad-bottom double-pad-top"> Enter additional details ';

    echo '<img class="wd-22 d-i-b hide icExpand gap-left relative top-3 pointer" src="/images/ic_expand.svg")/>';
    echo '<img class="wd-22 d-i-b icMinimize gap-left relative top-3 pointer" src="/images/ic_minimize.svg")/>';

echo '</h2>';



echo '<div class="full additionalDiv">';



    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

// Product

echo '<div class="relative pull-left leftPanelInfo">';

echo '<div class="relative pull-left">';
  echo '<span style="display: none" class="text-top">*Product</span>';
  echo '<ul class="dropdown bg-white d-i-b pull-left relative wd-280 product">';
            echo '<li>';
            echo '<a href="javascript:;" class="selected-text d-b users" value="All"><span id="productDropdown"class="d-i-b">*Product </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
            echo '</li>';
            echo '<li>';
             // echo $this->formRow($title);
            echo    '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                        
                        foreach($selectproduct as $product){ 
                            echo '<li>';
                                echo "<a href='javascript:;' value='$product[0]' shortCode='$product[1]'> $product[0] </a>";
                            echo '</li>';
                        }


            echo    '</ul>';

            echo '</li>';
        echo '</ul>';

        echo '<label class="opacity0 error producterror"> Please select product </label>';

    echo '</div>';
    

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------


    //Referral
    echo '<div class="relative pull-left">';
      echo '<span style="display: none" class="text-top">How did they hear about us?</span>';
      echo '<ul class="dropdown bg-white d-i-b pull-left relative wd-280 referral">';
            echo '<li>';
             echo '   <a href="javascript:;" class="selected-text d-b users" value="All"><span id="referralDropdown" class="d-i-b">How did they hear about us? </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
            echo '</li>';
            echo '<li>';
             // echo $this->formRow($title);
            echo    '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                        foreach($selectreferral as $referral){
                            echo '<li>';
                                echo "<a href='javascript:;' value='$referral[0]'><span class='ref-Img'><img class='pull-left' src=' $referral[1]'></span> $referral[0]</a>";                               
                            echo '</li>';
                        }
            echo    '</ul>';

            echo '</li>';
        echo '</ul>';

        echo '<label class="opacity0 error referralerror"> Please select how did they hear about us? </label>';

        echo '<select style="display:none" name="referral"><option value="" selected="selected"></option><select>';
    echo '</div>';


    // -----------------------------------------------------------------
    // -----------------------------------------------------------------


    // Referral Dropdown
    echo '<div class="relative pull-left hide"><span style="display: none" class="text-top">How did they hear about us? (Other)</span><input maxlength="45" autocomplete="Off" type="text" id="referralDropdownOther" placeholder="How did they hear about us? (Other)" /></div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // Referral Address 

    echo '<div class="relative pull-left">
            <span style="display: none" class="text-top">Referral</span>
            <a href="javascript:;" class="lookup absolute">Lookup</a>
            <input  maxlength="40" readOnly="readOnly" autocomplete="Off" type="text" placeholder="Referral" id="onlyReferral" />
        </div>';


   



    // -----------------------------------------------------------------
    // -----------------------------------------------------------------


//budget
echo '<div class="relative pull-left">';
  echo '<span style="display: none" class="text-top">*Budget </span>';
  echo '<ul class="dropdown bg-white d-i-b pull-left relative wd-280 budget">';
            echo '<li>';
             echo '   <a href="javascript:;" class="selected-text d-b users" value="All"><span id = "budgetDropdown"class="d-i-b">*Budget </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
            echo '</li>';
            echo '<li>';
             // echo $this->formRow($title);
            echo    '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                    foreach($selectbudget as $budget){ 
                        echo '<li>';
                            echo "<a href='javascript:;' value='$budget'> $budget </a>";
                        echo '</li>';
                    }
            echo    '</ul>';

            echo '</li>';
        echo '</ul>';
        echo '<label class="opacity0 error budgeterror"> Please select budget </label>';
    echo '</div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------   
    //AssignTo

         echo '<div class="relative pull-left">';
                echo '<span style="display: none" class="text-top">*Assign to</span>';
                echo '<ul class="dropdown bg-white d-i-b pull-left relative wd-280 assignToDiv">';
                    echo '<li>';
                        echo '<a href="javascript:;" class="selected-text d-b users" value="All"><span id = "assign_us_Dropdown" class="d-i-b">*Assign to </span><i class="icon-dropdown fs-7 pull-right d-i-b"></i></a>';
                    echo '</li>';
                    echo '<li>';
                    // echo $this->formRow($title);
                    echo    '<ul class="dropdownOptions bg-white absolute full-width dropdownheightSet hide" style="display:none;">';
                            
                    echo    '</ul>';

                    echo '</li>';
                echo '</ul>';
                echo '<label class="opacity0 error agenterror"> Please select assign to </label>';
        echo '</div>';



    // -----------------------------------------------------------------
    // -----------------------------------------------------------------

    // Reason

        echo '<div class="relative pull-left hide otherReasonDiv" style="display:none">';
            echo '<span style="display: none" class="text-top">Reason to skip next in line </span>';
            echo '<ul class="dropdown bg-white d-i-b pull-left relative wd-280">';
                    echo '<li>';
                     echo '   <a href="javascript:;" class="selected-text d-b users" value="Reason"><span id = "skip_reason_dropdown" class="d-i-b"></span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
                    echo '</li>';
                    echo '<li>';

                        echo  '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                            echo '<li><a href="javascript:;" value="Vacation leave"> Vacation leave </a></li>';
                            echo '<li><a href="javascript:;" value="Sick leave"> Sick leave </a></li>';
                            echo '<li><a href="javascript:;" value="Pregnancy"> Pregnancy </a></li>';
                            echo '<li><a href="javascript:;" value="Administrative leave"> Administrative leave </a></li>';
                            echo '<li><a href="javascript:;" value="Unpaid leave"> Unpaid leave </a></li>';
                            echo '<li class="otherReasonExplained"><a href="javascript:;" value="Other"> Other </a></li>';
                        echo  '</ul>';

                    echo '</li>';
                echo '</ul>';
        echo '</div>';

       

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------
    //ReferenceProduct

    echo '<div class="relative pull-left"><span style="display: none" class="text-top">Reference product</span><input autocomplete="off" type="text" name="ReferenceProduct" id="referrenceDropdown" class="ReferenceProduct" placeholder="Reference product" maxlength="30" value=""><span style="display: none">Reference product</span></div>';

    // -----------------------------------------------------------------
    // -----------------------------------------------------------------


    //Special Istruction
    echo '<div class="relative pull-left">';
        echo '<span style="display: none" class="text-top">Special instructions</span>';
            echo $this->formRow($form->get("special_instructions"));
        
    echo '</div>';






    
    // -----------------------------------------------------------------
    // -----------------------------------------------------------------
    
    

    // budget text

     echo '<div class="relative pull-left" hide style="display:none"><span style="display: none" class="text-top">Budget</span>
            <input type="text" name="Budget" id="BudgetText" autocomplete="off" class="Budget" placeholder="Budget" maxlength="30" value="">
            <p class="hideBudget hide"></p>
            <span style="display: none">Budget</span>
            <label class="opacity0 error budgeterror"> Please select budget </label>
            <label class="opacity0 error budgetForError"></label>
          </div>';






        echo '<div class="relative pull-left loadAgents hide">';
            echo '<span style="display: none" class="text-top">Assign to</span>';
            echo '<ul class="dropdown bg-white d-i-b pull-left relative wd-280">';
                    echo '<li>';
                     echo '   <a href="javascript:;" class="selected-text d-b users" value="Reason"><span class="d-i-b">Assign to</span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>';
                    echo '</li>';
                    echo '<li>';

                        echo  '<ul class="dropdownOptions bg-white absolute full-width" style="display:none;">';
                        echo  '</ul>';

                    echo '</li>';
                echo '</ul>';
        echo '</div>';

echo '</div>';

// -----------------------------------------------------------------      
// -----------------------------------------------------------------

echo '<div class="relative pull-left rightPanelInfo">';
    


   //specify_requirements  
     echo '<div class="relative pull-left">';
          echo '<span style="display: none" class="text-top">What they are looking for</span>';
          echo '<textarea  name="specify_requirements" id="specify_requirements" autocomplete="off" placeholder="What they are looking for" class="requirements" maxlength="1000"></textarea>';
          //echo $this->formRow($form->get("specify_requirements"));
     echo '</div>'; 


echo '</div>';


echo '</div>';

    echo '<div class="savenBookOptions pull-right triple-pad-right">';
        
        echo '<a href="javascript:;" class="wd-160 fs-14 button savenBookBtn lh-34 align-center robotomedium button btn-blue">Save and Book</a>'; 
        echo '<a href="javascript:;" class="wd-102 btn-green fs-14 button bg-white onlySaveBtn lh-34 align-center robotomedium thirtyfive-gapLeft">Save</a>'; 
            //echo '<label class="fs-10 relative bottom-3">or press <span class="color-darkGray robotomedium">ENTER</span></label>';
        echo '<a href="javascript:;" class="fs-14 onlyCancelBtn bg-white robotomedium gap-right color-gray10 thirtyfive-gapLeft">Cancel</a>';
        
    echo '</div>';

echo '</div>';

// .additional-details Div End
// .calendar Show On Book Div End

echo '<div class="calendarShowOnBook hide">'; // 

    echo '<h2 class="fs-24 color-green robotolight  hide bookingHeading pull-left hide"> Room Manager </h2>';

    // next-saveDiv Start
    echo'<div class="next-saveDiv full">';
        echo '<h2 class="fs-24 color-green robotolight showOnNewBooking"> Room Manager </h2>';
        echo '  <a href="javascript:;" class="btn-blue fs-14 button bg-white btn-bookNow open lh-34 align-center robotomedium pull-left gap-bottom hide">Book Now</a>';
        
        echo '<div class="pull-left fs-14 hide savedBooking double-gap-top">
                <span id="bookingDate" class="double-pad-right pull-left lh-34"></span>
                <a class="btn-blue button editBooking  pull-left wd-102" href="javascript:;" style="display:none">Edit</a> 
                <span class="pull-left  lh-34 double-pad-left half-gap-left pointer cancelBookedbooking">Cancel Booking</span>
            </div>';
            echo '<label class="hide pull-left pad-left lh-34 opacity0 color-red bookingError transition-ease-02 robotomedium">Please select a booking date</label>';
        echo '<div class="next-options pull-right triple-pad-right hide">';
            
            echo '<a href="javascript:;" class="btn-green fs-14 button bg-white btn-nextDetails lh-34 align-center robotomedium hide">Next</a>';
            echo '<a href="javascript:;" class="btn-green fs-14 button bg-white btn-saveDetails lh-34 align-center robotomedium "><input name="submit" type="submit" class="d-b full-width" id="submitbutton" value="Save"></a>'; 
            //echo '<label class="fs-10 relative bottom-3">or press <span class="color-darkGray robotomedium">ENTER</span></label>';
            echo '<a href="javascript:;" class="fs-14  btn-cancel bg-white robotomedium gap-right">Cancel</a>';
            
        echo '</div>';

    echo '</div>'; // next-saveDiv End

    // bookNowDiv Start

    
        echo $this->partial('dashboard/dashboard/bookingView.phtml');
    echo '</div>'; // next-saveDiv End
    // Adding Booking Div
    echo $this->partial('dashboard/dashboard/calendarView.phtml');


        
        
        
        
echo $this->form()->closeTag();


echo "<div class='agentOptions hide'>";
    echo '<div class="otherSelection lh-18" style="display:none">';
            echo '<p class="pad-bottom four-pad-top">You are going to Skip:</p>';
            echo '<div classs="full align-center" style="text-align: center;">';
            echo '<div style=" margin: 0 auto; min-width: 132px; display: inline-block;">';
                    echo "<span class='d-i-b half-pad-right v-a-m'><img class='pull-left inlineAgentImg' src='$AssignTo[1]' /></span>
                        <div class='d-i-b lh-14 half-pad-top v-a-t align-left'><label class='fs-10 color-lightGray'>Next in line:</label ><label class='fs-11 robotobold color-green inlineAgentName'>$AssignTo[0]</label></div>";
                echo '</div>';
            echo '</div>';
            echo '<p class="full one-half-pad-top half-pad-bottom">Please select a reason before to continue</p>';
            echo '<div class="full pad-top otherAgent">';
                        // Other Selection download
                        echo '<div class="Additionaldrodown relative  novalue">';
                                echo '<div class="additioanlSelection"><a href="javascript:;" value="Reasons">Reasons<span></span></a></div>';
                                echo '<div class="AdditionaldrodownList absolute" style="display:none">';
                                    echo '<p value="Vacation leave">Vacation leave</p>';
                                    echo '<p value="Sick leave">Sick leave</p>';
                                    echo '<p value="Pregnancy">Pregnancy</p>';
                                    echo '<p value="Administrative leave">Administrative leave</p>';
                                    echo '<p value="Unpaid leave">Unpaid leave</p>';
                                    echo '<p value="Other">Other</p>';
                                echo '</div>';
                                echo '<div style="display:none" class="full other-explain "><input type="text" placeholder="Please Explain"  maxlength="100"/></div>';

                            echo '</div>';

                 echo '</div>';

            echo '<div class="full double-pad-top triple-gap-top cancelSkip relative">';
                echo '<span class="selectReason opacity0 transition-ease-02">Please! select a reason</span>';
                echo '<span class="selectReason2 opacity0 transition-ease-02">Please! explain reason</span>';
                echo '<span class="btn-cancelAgent pointer d-i-b">Cancel</span>';
                echo '<span class="btn-skip button">Skip</span>';
                echo '<span class="btn-skip2 button hide" style="display:none">Skip</span>';
            echo '</div>';
        echo '</div>';
echo '</div>'; 



echo '<div class="thisLeadId" leadId=""></div>';
echo '<div id="appointmentId" appointmentId="0"></div>';


    

