<div class="addressContainer full robotoregular fs-14 formfields gap-top one-pad-top" style="display: none;">

    <div class="relative d-i-b v-a-t">
        <span style="display: none">Street</span>
            <input type="text" placeholder="Street" name="street" id="street" autocomplete="off" class="street" maxlength="45">
        <span style="display: none">Street</span>
    </div> <!-- Street Field End -->

    <!-- ========================================================= -->

    <div class="relative d-i-b v-a-t">
        <span style="display: none" class="text-top">State </span>
        <ul class="dropdown bg-white d-i-b pull-left relative wd-280 State">
            <li>
                <a href="javascript:;" class="selected-text d-b users" value="All"><span id="stateDropdown" class="d-i-b">State </span><i class="icon-dropdown fs-7 pull-right d-i-b "></i></a>
            </li>
            <li>
                <ul class="dropdownOptions bg-white absolute full-width" style="display:none;">
                        <li><a href='javascript:;' value='ACT'>ACT</a></li>
                        <li><a href='javascript:;' value='NSW'>NSW</a></li>
                        <li><a href='javascript:;' value='NT'>NT</a></li>
                        <li><a href='javascript:;' value='QLD'>QLD</a></li>
                        <li><a href='javascript:;' value='WA'>WA</a></li>
                        <li><a href='javascript:;' value='TAS'>TAS</a></li>
                        <li><a href='javascript:;' value='VIC'>VIC</a></li>
                        <li><a href='javascript:;' value='SA'>SA</a></li>
                </ul>
            </li>
        </ul>
        <label class="opacity0 error stateerror"> Please select State </label>
    </div> <!-- State Div End -->

    <!-- ========================================================= -->


    <div class="relative d-i-b v-a-t">
        <span style="display: none">City</span>
            <input type="text" placeholder="City" name="City" id="cityValue" autocomplete="off" class="cityValue" maxlength="30">
        <span style="display: none">City</span>
    </div> <!-- City Div End -->

    <!-- ========================================================= -->


    <div class="relative d-i-b v-a-t">
        <span style="display: none">Zip</span>
            <input type="text" placeholder="Zip" name="Zip" id="Zip" autocomplete="off" class="Zip" maxlength="6">
        <span style="display: none">Zip</span>
    </div> <!-- Zip Field End -->


</div><!-- Address Container End -->

