<div class="bookNowDiv full hide relative" style="display: none">
	<!-- Heading View -->
	<div class="full bookNowMain">
		<h2 class="fs-24 color-green robotolight double-pad-bottom  full relative"> 
			<span class="pull-left">Calendar</span> 
			<label class="hide pull-left pad-left color-red bookingError fs-12 transition-ease-02 gap-top two-pad-top robotomedium opacity0">Please! select a booking date</label>
			<label class="pull-left pad-left color-red timeSlotError absolute fs-12 transition-ease-02 gap-top two-pad-top robotomedium opacity0">All rooms are booked.</label>
			<div class="bookingViewIcon d-i-b hide opacity0">
					<img class="wd-24 d-i-b double-gap-left relative top-4" src="<?php echo $this->serverUrl('/images/ic_calendar.svg'); ?>" />
					<a href="javascript:;" class="color-blue fs-14 robotoregular relative bottom-2">calendar view</a> 
			</div>
		</h2>

		<!-- ========================================================= -->

		<!-- Suggested Date -->
		<div class="full half-gap-bottom questionView relative hide">
			
			<div class="absolute fs-10 AM-heading left-0">
				<span>8 AM</span>
				<span>9 AM</span>
				<span>10 AM</span>
				<span>11 AM</span>
			</div>
			<div class="absolute fs-10 PM-heading left-0 hide">
				<span>12 PM</span>
				<span>1 PM</span>
				<span>2 PM</span>
				<span>3 PM</span>
				<span>4 PM</span>
			</div>
			<div id='calendar2' class="calendar2 amHeight"></div>	
		</div>

		<!-- ========================================================= -->

	    <a href="javascript:;" class="btn-green fs-14 button bg-white btn-saveBooking open lh-34 align-center robotomedium pull-left gap-bottom">Book</a>
	    <a href="javascript:;" class="fs-14 cancelBooking bg-white robotomedium color-darkGray lh-34 triple-gap-left pad-left">Cancel</a>

	    <!-- ========================================================= -->
	    
	    <div class="next-options pull-right triple-pad-right disablebtns">
	        <a href="javascript:;" class="color-green fs-14 button bg-white btn-disableSave lh-34 align-center robotomedium">Save</a>
	        <label class="fs-10"><span class="color-lightGray">or press</span> <span class="color-darkGray robotomedium disableEnter">ENTER</span></label>
	    </div>

	</div>
    
    <div class="coverAreaBooking hide"></div>

</div>

<div id="newCalendar">
	
</div>





<div class="NewCalendarContainer full openNow relative">

		<h2 class="fs-24 color-green robotolight bookingHeading" style="display: none"> Room Manager </h2>
		<div class="full triple-pad-top half-pad-bottom">
	        <label class="pull-left half-gap-right lh-28 color-darkGray two-pad-right fs-14">Rooms</label>
	        <div class="d-i-b bookingRooms">

	        	<a href="javascript:;" class="active all-rooms" value="All Rooms">All Rooms</a>
		        <a href="javascript:;" class="room-1" value="Room 1">Room 1</a>
		        <a href="javascript:;" class="room-2" value="Room 2">Room 2</a>
		        <a href="javascript:;" class="room-3" value="Room 3">Room 3</a>
		        <a href="javascript:;" class="room-4" value="Room 4">Room 4</a>
		        
			</div>
			<div class="colorDefinition pull-right hide">
				<label>Past date</label><span></span>
				<label>Agent on leave</label><span></span>
			</div>
	    </div><!-- Div End -->

	    <!-- ======================================================= -->
	    <!-- ======================================================= -->

	    <div class="calendarHead full double-gap-top relative">
			
			<div class="weeklyDates fs-20">
				<label class="bg-white gap-right pointer arrowPrev" date-scroll="prev"><img src="images/arrow-point-to-leftHeadBar.png" /></label>
				<span class="calendarWeeklyDate">  </span>
				<label class="bg-white gap-left pointer arrowNext" date-scroll="next"><img src="images/arrow-point-to-rightHeadBar.png" /></label>
			</div><!-- Div weeklyDates End -->

			<div class="cancelNewBooking absolute">
				<a href="javascript:;" class="btn-green fs-14 button bg-white lh-34 align-center robotomedium">Cancel</a>
			</div><!-- Div saveNewBooking End -->	   
			<div class="saveNewBooking absolute">
				<a href="javascript:;" class="btn-green fs-14 button bg-white lh-34 align-center robotomedium">Save</a>
			</div><!-- Div saveNewBooking End -->	    	

	    </div><!-- Div CalendarHead End -->

	    <!-- ======================================================= -->
	    <!-- ======================================================= -->

	    <div id="NewCalendar" class="NewCalendar full">

	    	<div class="hourContainer">
	    		<p class="fs-14">Hour</p>

	    		<div class="hoursList">
	    			<label>8:00 am</label>
	    			<label>9:00 am</label>
	    			<label>10:00 am</label>
	    			<label>11:00 am</label>
	    			<label>12:00 pm</label>
	    			<label>1:00 pm</label>
	    			<label>2:00 pm</label>
	    			<label>3:00 pm</label>
	    			<label>4:00 pm</label>
	    			<label>5:00 pm</label>
	    			<label class="till6">6:00 pm</label>
	    		</div><!-- Div hoursList End -->

	    	</div>

	    	<!-- ======================================================= -->
	   		<!-- ======================================================= -->

	    	<div class="loadnewCalendar full" id="loadnewCalendar">

    			<div class="dayMonday daysCalendar pull-left 1" titleDay="dayMonday">
    				<p class="align-center headerPart">Monday 6/15</p>
    				<div class="daysSlider">
    					<div class="roomsContainer relative transition-ease-02">
	    					<label>ROOM 1</label>
	    					<label class="room2">ROOM 2 <img src="images/arrow-point-to-right.png" /></label>
	    					<label class="room3">ROOM 3 <img src="images/arrow-point-to-left.png" /></label>
	    					<label>ROOM 4</label>
    					</div>
    				</div>
    			</div><!-- Div dayMonday End -->

    			<!-- ======================================================= -->

    			<div class="dayTuesday daysCalendar pull-left 2" titleDay="dayTuesday">
    				<p class="align-center headerPart">Tuesday 6/16</p>
    				<div class="daysSlider">
    					<div class="roomsContainer relative transition-ease-02">
	    					<label>ROOM 1</label>
	    					<label class="room2">ROOM 2 <img src="images/arrow-point-to-right.png" /></label>
	    					<label class="room3">ROOM 3 <img src="images/arrow-point-to-left.png" /></label>
	    					<label>ROOM 4</label>
    					</div>
    				</div>
    			</div><!-- Div dayTuesday End -->

    			<!-- ======================================================= -->

    			<div class="dayWednesday daysCalendar pull-left 3" titleDay="dayWednesday">
    				<p class="align-center headerPart">Wednesday 6/17</p>
    				<div class="daysSlider">
    					<div class="roomsContainer relative transition-ease-02">
	    					<label>ROOM 1</label>
	    					<label class="room2">ROOM 2 <img src="images/arrow-point-to-right.png" /></label>
	    					<label class="room3">ROOM 3 <img src="images/arrow-point-to-left.png" /></label>
	    					<label>ROOM 4</label>
    					</div>
    				</div>
    			</div><!-- Div dayWednesday End -->

    			<!-- ======================================================= -->

    			<div class="daythursday daysCalendar pull-left 4" titleDay="daythursday">
    				<p class="align-center headerPart">Thursday 6/18</p>
    				<div class="daysSlider">
    					<div class="roomsContainer relative transition-ease-02">
	    					<label>ROOM 1</label>
	    					<label class="room2">ROOM 2 <img src="images/arrow-point-to-right.png" /></label>
	    					<label class="room3">ROOM 3 <img src="images/arrow-point-to-left.png" /></label>
	    					<label>ROOM 4</label>
    					</div>
    				</div>
    			</div><!-- Div daythursday End -->

    			<!-- ======================================================= -->

    			<div class="dayFriday daysCalendar pull-left 5" titleDay="dayFriday">
    				<p class="align-center headerPart">Friday 6/19</p>
    				<div class="daysSlider">
    					<div class="roomsContainer relative transition-ease-02">
	    					<label>ROOM 1</label>
	    					<label class="room2">ROOM 2 <img src="images/arrow-point-to-right.png" /></label>
	    					<label class="room3">ROOM 3 <img src="images/arrow-point-to-left.png" /></label>
	    					<label>ROOM 4</label>
    					</div>
    				</div>
    			</div><!-- Div dayFriday End -->

    			<!-- ======================================================= -->

    			<div class="daySaturday daysCalendar pull-left 6" titleDay="daySaturday">
    				<p class="align-center headerPart">Saturday 6/20</p>
    				<div class="daysSlider">
    					<div class="roomsContainer relative transition-ease-02">
	    					<label>ROOM 1</label>
	    					<label class="room2">ROOM 2 <img src="images/arrow-point-to-right.png" /></label>
	    					<label class="room3">ROOM 3 <img src="images/arrow-point-to-left.png" /></label>
	    					<label>ROOM 4</label>
    					</div>
    				</div>
    			</div><!-- Div daySaturday End -->

    			<!-- ======================================================= -->

    			<div class="daySunday daysCalendar pull-left 7" titleDay="daySunday">
    				<p class="align-center headerPart">Sunday 6/21</p>
    				<div class="daysSlider">
    					
    				</div>
    			</div><!-- Div daySunday End -->

    		</div><!-- Div loadnewCalendar End -->

    		<!-- ======================================================= -->
    		<!-- ======================================================= -->
    		<!-- ======================================================= -->

    		<div class="loadnewCalendarContent full" id="loadnewCalendarContent">

    			<div class="mondayContent daysContent 1">
    				
    			
					<div class="dayMonday daysCalendar pull-left" titleDay="dayMonday" dayName="Monday">
	    				
	    				<div class="daysContentSlider 8am 8" time="8:00 - 9:00 AM" startingTime="8">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 8am End -->
	    				
	    				<div class="daysContentSlider 9am 9" time="9:00 - 10:00 AM" startingTime="9">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 9am End -->

	    				<div class="daysContentSlider 10am 10" time="10:00 - 11:00 AM" startingTime="10">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 10am End -->

	    				<div class="daysContentSlider 11am 11" time="11:00 - 12:00 PM" startingTime="11">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 12pm 12" time="12:00 - 1:00 PM" startingTime="12">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 1pm 1" time="1:00 - 2:00 PM" startingTime="1">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 2pm 2" time="2:00 - 3:00 PM" startingTime="2">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 3pm 3" time="3:00 - 4:00 PM" startingTime="3">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 4pm 4" time="4:00 - 5:00 PM" startingTime="4">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 5pm 5" time="5:00 - 6:00 PM" startingTime="5">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->


	    			</div><!-- Div dayMonday End -->

	    			
    			</div><!-- Div mondayContent End -->

    			<!-- ======================================================= -->

    			<div class="tuesdayContent daysContent 2">
    				
    			
					<div class="dayTuesday daysCalendar pull-left" titleDay="dayTuesday" dayName="Tuesday">
	    				
	    				<div class="daysContentSlider 8am 8" time="8:00 - 9:00 AM" startingTime="8">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 8am End -->
	    				
	    				<div class="daysContentSlider 9am 9" time="9:00 - 10:00 AM" startingTime="9">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 9am End -->

	    				<div class="daysContentSlider 10am 10" time="10:00 - 11:00 AM" startingTime="10">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 10am End -->

	    				<div class="daysContentSlider 11am 11" time="11:00 - 12:00 PM" startingTime="11">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 12pm 12" time="12:00 - 1:00 PM" startingTime="12">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 1pm 1" time="1:00 - 2:00 PM" startingTime="1">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 2pm 2" time="2:00 - 3:00 PM" startingTime="2">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 3pm 3" time="3:00 - 4:00 PM" startingTime="3">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 4pm 4" time="4:00 - 5:00 PM" startingTime="4">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 5pm 5" time="5:00 - 6:00 PM" startingTime="5">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->


	    			</div><!-- Div dayTuesday End -->

	    			
    			</div><!-- Div tuesdayContent End -->

    			<!-- ======================================================= -->

    			<div class="wednesdayContent daysContent 3">
    				
    			
					<div class="dayWednesday daysCalendar pull-left" titleDay="dayWednesday" dayName="Wednesday">
	    				
	    				<div class="daysContentSlider 8am 8" time="8:00 - 9:00 AM" startingTime="8">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 8am End -->
	    				
	    				<div class="daysContentSlider 9am 9" time="9:00 - 10:00 AM" startingTime="9">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 9am End -->

	    				<div class="daysContentSlider 10am 10" time="10:00 - 11:00 AM" startingTime="10">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 10am End -->

	    				<div class="daysContentSlider 11am 11" time="11:00 - 12:00 PM" startingTime="11">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 12pm 12" time="12:00 - 1:00 PM" startingTime="12">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 1pm 1" time="1:00 - 2:00 PM" startingTime="1">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 2pm 2" time="2:00 - 3:00 PM" startingTime="2">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 3pm 3" time="3:00 - 4:00 PM" startingTime="3">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 4pm 4" time="4:00 - 5:00 PM" startingTime="4">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 5pm 5" time="5:00 - 6:00 PM" startingTime="5">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->


	    			</div><!-- Div dayWednesday End -->

	    			
    			</div><!-- Div wednesdayContent End -->

    			<!-- ======================================================= -->

    			<div class="thursdayContent daysContent 4">
    				
    			
					<div class="daythursday daysCalendar pull-left" titleDay="daythursday" dayName="Thursday">
	    				
	    				<div class="daysContentSlider 8am 8" time="8:00 - 9:00 AM" startingTime="8">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 8am End -->
	    				
	    				<div class="daysContentSlider 9am 9" time="9:00 - 10:00 AM" startingTime="9">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 9am End -->

	    				<div class="daysContentSlider 10am 10" time="10:00 - 11:00 AM" startingTime="10">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 10am End -->

	    				<div class="daysContentSlider 11am 11" time="1100 - 12:00 PM" startingTime="11">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 12pm 12" time="12:00 - 1:00 PM" startingTime="12">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 1pm 1" time="1:00 - 2:00 PM" startingTime="1">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 2pm 2" time="2:00 - 3:00 PM" startingTime="2">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 3pm 3" time="3:00 - 4:00 PM" startingTime="3">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 4pm 4" time="4:00 - 5:00 PM" startingTime="4">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 5pm 5" time="5:00 - 6:00 PM" startingTime="5">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->


	    			</div><!-- Div thursday End -->

	    			
    			</div><!-- Div thursdayContent End -->

    			<!-- ======================================================= -->

    			<div class="fridayContent daysContent 5">
    				
    			
					<div class="dayFriday daysCalendar pull-left" titleDay="dayFriday" dayName="Friday">
	    				
	    				<div class="daysContentSlider 8am 8" time="8:00 - 9:00 AM" startingTime="8">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 8am End -->
	    				
	    				<div class="daysContentSlider 9am 9" time="9:00 - 10:00 AM" startingTime="9">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 9am End -->

	    				<div class="daysContentSlider 10am 10" time="10:00 - 11:00 AM" startingTime="10">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 10am End -->

	    				<div class="daysContentSlider 11am 11" time="11:00 - 12:00 PM" startingTime="11">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 12pm 12" time="12:00 - 1:00 PM" startingTime="12">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 1pm 1" time="1:00 - 2:00 PM" startingTime="1">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 2pm 2" time="2:00 - 3:00 PM" startingTime="2">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 3pm 3" time="3:00 - 4:00 PM" startingTime="3">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 4pm 4" time="4:00 - 5:00 PM" startingTime="4">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 5pm 5" time="5:00 - 6:00 PM" startingTime="5">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->


	    			</div><!-- Div dayFriday End -->

	    			
    			</div><!-- Div fridayContent End -->

    			<!-- ======================================================= -->

    			<div class="saturdayContent daysContent 6">
    				
    			
					<div class="daySaturday daysCalendar pull-left" titleDay="daySaturday" dayName="Saturday">
	    				
	    				<div class="daysContentSlider 8am 8" time="8:00 - 9:00 AM" startingTime="8">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 8am End -->
	    				
	    				<div class="daysContentSlider 9am 9" time="9:00 - 10:00 AM" startingTime="9">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 9am End -->

	    				<div class="daysContentSlider 10am 10" time="10:00 - 11:00 AM" startingTime="10">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 10am End -->

	    				<div class="daysContentSlider 11am 11" time="11:00 - 12:00 PM" startingTime="11">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 12pm 12" time="12:00 - 1:00 PM" startingTime="12">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 1pm 1" time="1:00 - 2:00 PM" startingTime="1">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 2pm 2" time="1:00 - 3:00 PM" startingTime="2">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 3pm 3" time="3:00 - 4:00 PM" startingTime="3">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 4pm 4" time="4:00 - 5:00 PM" startingTime="4">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->

	    				<div class="daysContentSlider 5pm 5" time="5:00 - 6:00 PM" startingTime="5">
	    					<div class="roomsContainer relative transition-ease-02">
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<label><a class="addBookingLink" href="javascript:;"><i class="icon-addBookingLink fs-15"></i></a></label>
		    					<p class="borderPart"></p>
	    					</div>
	    				</div><!-- Div 11am End -->


	    			</div><!-- Div daySaturday End -->

	    			
    			</div><!-- Div saturdayContent End -->

    			<!-- ======================================================= -->

    			<div class="sundayContent daysContent 7">
    				
    			
					<div class="daySunday daysCalendar pull-left" titleDay="daySunday">
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
						<span class="sundayLine"></span>
	    			</div><!-- Div daySunday End -->

	    			
    			</div><!-- Div sundayContent End -->

    			<!-- ======================================================= -->

    		</div><!-- Div loadnewCalendarContent End -->

	    </div>

	    <!-- ======================================================= -->
	    <!-- ======================================================= -->


</div><!-- Div NewCalendarContainer End -->


<div class="hide fixed addBookingPopup">



</div>
