<div class="full dashboard-header ">

    <div class="d-i-b double-pad-left triple-gap-left newactions absolute">
        <a href="javascript:;" class="tabs green new-Lead "><i class="icon-newLead"></i> <span>New lead</span> </a>
        <a href="javascript:;" class="tabs green new-Leave hide"><i class="icon-newLead"></i> <span> New leave</span> </a>
    </div>
    
    <div class="middleTabs">
        <a href="javascript:;" class="tabs blue leaveTab"> <i class="icon-leave"></i> <span>Leaves</span> </a>
        <a href="javascript:;" class="tabs blue active leadTab"><i class="icon-leads"></i> <span>Leads</span> </a>
        <a href="javascript:;" class="tabs blue dashboardTab hide"><i class="icon-dashboard"></i> <span>Dashboard</span> </a>
    </div>

    <div class="absolute right-0 dateSelected d-i-b top-0 triple-pad-right triple-gap-right fs-14 robotomedium">
    </div>

</div>