<?php
/**
 * Created by PhpStorm.
 * User: Quan Lee
 * Date: 12/7/16
 * Time: 10:53 AM
 */

?>

<div class="contentArea hide">
    <?php
    $title = 'Dashboard';
    $this->headTitle($title);
    ?>
    <div class="mainLoginForm color-darkGray robotomedium">
    	<div class="loginInner">
        	<h1><?php echo $this->escapeHtml($title); ?></h1>
        	<div class="loginFormFields">
        		<a href="/logout" class="cmnBtn" style="margin-top:0">Logout</a>
        	</div>
    	</div>
    </div>
</div>

<?php
    echo $this->partial('dashboard/dashboard/headerTabs.phtml');
    echo $this->partial('dashboard/dashboard/leaves.phtml');
    echo $this->partial('dashboard/dashboard/newLeave.phtml');
    echo $this->partial('dashboard/dashboard/leads.phtml');
    echo $this->partial('dashboard/dashboard/dashboard.phtml');
    echo $this->partial('dashboard/dashboard/leadDetail.phtml');

?>
<div class="newLead full robotoregular transition-ease-05 maxHeightShow maxHeightHide">
        <div class="innerContainer bg-white full">
        <div class="full searchArea double-pad-bottom hald-gap-bottom relative hideOnSavenBook">
            <h2 class="fs-24 color-green robotolight one-half-pad-bottom"> Search Existing </h2>.
            <div class="d-i-b pull-left relative searchContainer">
                <input type="text" class="relative lh-32 fs-14 color-darkGray double-pad-left double-pad-right searchField" >
                <i class="icon-search fs-18 absolute right-15 top-7 pointer"></i>   
                <div id="searchResults" class=" absolute"></div>
            </div>
        </div>    
        <h2 class="fs-24 color-green robotolight hideOnSavenBook"> Enter basic contact info </h2>
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('dashboard', array('action' => 'index')));
                echo $this->partial('dashboard/dashboard/_form.phtml', array( 
                    'form' =>$form,
                ));
            ?>
        </div>
        <div class="showloading" style="display: none;">
            <img src="/images/loading.gif">
        </div>

</div>


<div class="calendarLoad full hide">
    
</div>

<div class="mainLoader" style="display: none">
        <img src="/images/loading.gif">
</div>

<div class="showMessage">
    <div> All rooms are booked </div>
</div>
<div class="showLookups hide" style="display: none">
    <div class="LookupBG"></div>
    <div class="showLookupsInner">
        <p class="customerHeading">Customer List <span>x</span> </p>
        <div class="customerList">
            <table id="datatable" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="ShowPopup calcelLeadInfo margin-auto align-center fixed left-0 right-0 bg-white transition-ease-05">
    <div class="double-pad-bottom fs-14 lh-24"> Are you sure you want to cancel this booking? All Information will be lost. </div>
    <a href="javascript:;" class="wd-102 btn-green fs-12 button bg-white yesCancelBooking align-center robotomedium">Yes</a>
    <a href="javascript:;" class="wd-102 btn-red fs-12 button bg-white NoCancelBooking align-center robotomedium thirtyfive-gapLeft">No</a>
</div>