<div class="leavesContainer full robotoregular fs-14 hide">
    <!-- Leaves Filter -->
    <div class="full leavesFilter relative">

        <div class="leavesHeader pull-left">
            <div class="pull-left Consultation double-pad-right"><span></span> Booked in for a Consultation </div>
            <div class="pull-left Rosteres double-pad-right"><span></span> Rosteres Day Off - RDO </div>
            <div class="pull-left annualLeaveTab double-pad-right"><span></span> Annual Leave - AL </div>
            <div class="pull-left sickDay double-pad-right"><span></span> Sick Day </div>
            <div class="pull-left other double-pad-right"><span></span> Other </div>
        </div>

        <!-- ========================================================= -->

        <div class=" pull-left sellerAgents robotomedium">
            <span class="pull-left triple-pad-left gap-left pad-right">Seller</span>
            <div class="pull-left">
                <a href="javascript:;" value="Natalie">Natalie</a>
                <a href="javascript:;" value="Bec">Bec</a>
                <a href="javascript:;" value="Shelley">Shelley</a>
                <a href="javascript:;" value="Aaron">Aaron</a>
            </div>
        </div>

        <!-- ========================================================= -->

        <div class="pull-right leaveTime">
            <span class="leaveMonth pointer robotomedium fs-17 one-half-pad-right"><span month="1">January</span> <i class="icon-downarrow fs-14 half-pad-left bold"></i> </span>
            <div class="monthDropdown absolute leavedropdown" hidden="hidden">
                <span value="January" month="1">January</span>
                <span value="February" month="2" >February</span>
                <span value="March" month="3" >March</span>
                <span value="April" month="4" >April</span>
                <span value="May" month="5" >May</span>
                <span value="June" month="6" >June</span>
                <span value="July" month="7" >July</span>
                <span value="August" month="8" >August</span>
                <span value="September" month="9" >September</span>
                <span value="October" month="10" >October</span>
                <span value="November" month="11" >November</span>
                <span value="December" month="12" >December</span>
            </div>
            <span class="leaveYear  pointer  robotomedium fs-17"><span year=""></span> <i class="icon-downarrow fs-14 half-pad-left  bold"></i> </span>
            <div class="yearDropdown absolute leavedropdown" hidden="hidden">
            </div>
        </div>

        <!-- ========================================================= -->

    </div>
    
    <!-- Leaves Content -->

    <div class="full triple-padded all-Leaves-Content relative">

        <div class="content-heading full robotomedium fs-14">
            <span>Sunday</span>
            <span>Monday</span>
            <span>Tuesday</span>
            <span>Wednesday</span>
            <span>Thursday</span>
            <span>Friday</span>
            <span>Saturday</span>
        </div>

        <!-- ========================================================= -->

        <div class="leaveContent full">
            <div class="leavesDetail" index="0"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="1"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="2"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="3"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="4"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="5"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="6"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="7"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="8"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="9"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="10"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="11"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="12"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="13"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="14"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="15"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="16"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="17"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="18"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="19"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="20"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="21"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="22"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="23"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="24"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="25"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="26"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="27"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="28"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="29"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="30"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="31"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="32"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="33"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="34"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="35"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="36"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="37"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="38"><span class="dateArea"></span><div class="agentLeaves"></div></div>
            <div class="leavesDetail" index="39"><span class="dateArea"></span><div class="agentLeaves"></div></div>
        </div>
        
        <div class="leavesLoading loading absolute">
            <img src="/images/loading.gif">
        </div>
    </div>
</div>

