<div class="newLeaveContainer full robotoregular fs-14 " style="display: none">
    <!-- Leaves Filter -->
    <div class="full  innerContainer bg-white relative">

        <div class="relative pull-left calendarLeaveField">
            <span style="display: none;">Select a date for range number*</span>


            <input type="text" name="dateRange" id="dateRange" readonly="readonly" placeholder="Select a date for range number" class="dateRange" value="">

            <i class="icon-calendarClose fs-24 closeCalendarIcon absolute z-index1"></i>

            <label class="opacity0 showError">Please select a date</label>
            <div class="calendarLeave absolute transition-ease-05 maxHeightShow maxHeightHide">
                <div class="leaveCalendar full"></div>
                
            </div>
        </div>
        
        <!-- --------------- -->

        <div class="relative d-i-b v-a-t">
            <span style="display: none" class="text-top">Assign to</span>
            <ul class="dropdown bg-white d-i-b pull-left relative wd-280 assignToDivLeave">
                <li class="nextInline">
                    <a href="javascript:;" class="selected-text d-b leaveAgent" value="All">
                        <span id="assign_us_Dropdown2" class="d-i-b">Assign to </span>
                        <i class="icon-dropdown fs-7 pull-right d-i-b"></i>
                    </a>
                </li>
                <li>
                    <ul class="dropdownOptions bg-white absolute full-width dropdownheightSet" style="display: block;">
                        <li class="nextInline">
                            <a href="javascript:;" id="28" value="Laura Wang">
                            <span>
                                <img class="pull-left" src="/profile_image/sampleUser.png">
                                <span>
                                    <div>
                                        <label>Laura Wang</label>
                                    </div>
                                </span>
                            </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" id="29" value="Angelyn Atchazo">
                                <span>
                                    <img class="pull-left" src="/profile_image/sampleUser.png">
                                    <span>
                                        <div>
                                            <label>Angelyn Atchazo</label>
                                        </div>
                                    </span>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" id="30" value="Shelley Bedarov">
                                <span>
                                    <img class="pull-left" src="/profile_image/sampleUser.png">
                                    <span>
                                        <div>
                                            <label>Shelley Bedarov</label>
                                        </div>
                                    </span>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" id="35" value="Alan Hashem">
                                <span>
                                    <img class="pull-left" src="/profile_image/sampleUser.png"><span>
                                        <div>
                                            <label>Alan Hashem</label>
                                        </div>
                                    </span>
                                </span>
                            </a>
                        </li>
                        
                    </ul>
                </li>
            </ul>

            <label class="opacity0 showError"> Please select assign to </label>
        </div>

        <!-- --------------- -->

        <div class="relative d-i-b v-a-t">
            <span style="display: none;" class="text-top">Reason </span>
            <ul class="dropdown bg-white d-i-b pull-left relative wd-280 Reason">
                <li>   
                    <a href="javascript:;" class="selected-text d-b leaveReason" value="All">
                        <span id="Reasons" class="d-i-b">Reason</span>
                        <i class="icon-dropdown fs-7 pull-right d-i-b "></i>
                    </a>
                </li>
                <li>
                    <ul class="dropdownOptions bg-white absolute full-width" style="display: block;">
                        <li> <a href="javascript:;" value="Vacation leave"> Vacation leave </a> </li>
                        <li> <a href="javascript:;" value="Sick leave"> Sick leave </a> </li>
                        <li> <a href="javascript:;" value="Pregnancy"> Pregnancy </a> </li>
                        <li> <a href="javascript:;" value="Administrative leave"> Administrative leave </a> </li>
                        <li> <a href="javascript:;" value="Unpaid leave"> Unpaid leave </a> </li>
                        <li> <a href="javascript:;" value="Other"> Other </a> </li>
                    </ul>
                </li>
            </ul>
            <label class="opacity0 showError"> Please select Reason </label>
        </div>

   

        <div class="leaveNext-options pull-right triple-pad-right half-pad-top">
            <a href="javascript:;" class="btn-green fs-14 button bg-white btn-saveDetailsLeave lh-34 align-center robotomedium">Save</a>
            <label class="fs-10">or press <span class="color-darkGray robotomedium">ENTER</span>
            </label>
            <a href="javascript:;" class="fs-14  btn-cancelLeave bg-white robotomedium ">Cancel</a>
        </div>


    </div>

</div>

