<!-- Add tem Light Box -->
<div class="lightBox" id="addItem">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Add Diamond<a href="javascript:;" class="closePopup" title="Close">X</a></div>	
    <div class="lightBoxContent fl width100p">
	<?php
		$inventoryForm->prepare();
		echo $this->form()->openTag($inventoryForm);
		echo $this->formElement($this->inventoryForm->get('supplier_id'));
		echo $this->formElement($this->inventoryForm->get('image'));
		echo $this->formElement($this->inventoryForm->get('invoice'));
	?>
      <div class="commonForm rowSpace addItemForm">
          <div class="alphaClmn">
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('diamond_type')->getLabel(); ?></label>
              <div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('diamond_type')); ?></div></div>
            </div>
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('cert_no')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('cert_no')); ?></div>
            </div>
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('cert_url')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('cert_url')); ?></div>
            </div>
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('video_url')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('video_url')); ?></div>
            </div>
            <div class="formRow" id="color_type" style="display:none;">
              <label class="labelControll"><?php echo $this->inventoryForm->get('color')->getLabel(); ?></label>
              <div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('color')); ?></div></div>
            </div>
			<div class="formRow" id="white_type" style="display:none;">
              <label class="labelControll"><?php echo $this->inventoryForm->get('white_type')->getLabel(); ?></label>
              <div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('white_type')); ?></div></div>
            </div>
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('shape')->getLabel(); ?></label>
              <div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('shape')); ?></div></div>
            </div>
			<div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('polish')->getLabel(); ?></label>
              <div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('polish')); ?></div></div>
            </div>
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('symmetry')->getLabel(); ?></label>
              <div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('symmetry')); ?></div></div>
            </div>
			<div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('cut')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('cut')); ?></div>
            </div>
			<div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('carat')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('carat')); ?></div>
            </div>
			<div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('clarity')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('clarity')); ?></div>
            </div>
            <div class="hilightSection">
                <h3>For Coloured Diamonds Only</h3>
                <div class="formRow">
					<label class="labelControll"><?php echo $this->inventoryForm->get('intensity')->getLabel(); ?></label>
					<div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('intensity')); ?></div></div>
				</div>
				<div class="formRow">
					<label class="labelControll"><?php echo $this->inventoryForm->get('overtone')->getLabel(); ?></label>
					<div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('overtone')); ?></div></div>
				</div>
            </div>
          </div>
          <div class="betaClmn">
			<div class="formRow">
				<label class="labelControll"><?php echo $this->inventoryForm->get('lab')->getLabel(); ?></label>
				<div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->inventoryForm->get('lab')); ?></div></div>
			</div>
			<div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('depth')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('depth')); ?></div>
            </div>
			<div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('table')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('table')); ?></div>
            </div>
			<div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('flurosence')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('flurosence')); ?></div>
            </div>
			<div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('measurement')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('measurement')); ?></div>
            </div>
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('description')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('description')); ?></div>
            </div>
             <div class="formRow">
              <label class="labelControll">Upload Image</label>
              <div class="inputDiv">
                <div class="inputfile"><span class="cmnBtn blueBtn marL0">Upload</span><input type="file" name="item_image" id="item_image" /></div>
                <div class="uploadedImgDisplay" id="preview"></div>
              </div>
            </div>          
          </div>
          
          <div class="headSettings">
          <h2 class="cmnHeader">Head Settings</h2>
          <div class="alphaClmn">
            <div class="formRow">
              <label class="labelControll">Attach Invoice</label>
              <div class="inputDiv"><div class="inputfile"><span class="cmnBtn blueBtn marL0">Upload</span><input type="file" name="item_invoice" id="item_invoice" /></div>
			  <div class="uploadedInvoiceDisplay" id="invoicePreview"></div></div>
            </div>
            <div class="formRow">
               <label class="labelControll"><?php echo $this->inventoryForm->get('supplier_name')->getLabel(); ?></label>
                  <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('supplier_name')); ?><a href="javascript:;" class="cmnBtn blueBtn lightBoxClick" data-popup="supplierlookup" onclick="suppliersLookup(20, 'supplier_id', 'supplier_name');">Lookup</a></div>
            </div>
           </div>           
          <div class="betaClmn">
            <div class="formRow">
              <label class="labelControll"><?php echo $this->inventoryForm->get('price')->getLabel(); ?></label>
              <div class="inputDiv"><?php echo $this->formElement($this->inventoryForm->get('price')); ?></div>
            </div>            
           </div> 
           </div>           
			<div class="formButtons tc fl width100p marB30">
				<?php echo $this->formElement($this->inventoryForm->get('save')); ?>
				<?php echo $this->formElement($this->inventoryForm->get('cancel')); ?>			
			</div>
    </div>
	<?php echo $this->form()->closeTag(); ?>
  </div>
  
</div>
</div>
<!-- Add tem Light Box End-->

<!--BOF Supplier lookup list-->
<div class="lightBox" id="supplierlookup">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Supplier Lookup <a href="javascript:;" class="closePopup" title="Close">X</a></div>
    <div class="lightBoxContent fl width100p lookupPopup padB105">
      <div class="mainSearch">
        <input name="lookupsrc" id="lookupsrc" type="text" class="searchInput" placeholder="Search..">
        <input type="button" class="inputGo" value="Go!" onclick="suppliersLookup(20, 'supplier_id', 'supplier_name', $('#lookupsrc').val());" id="supplierLookupSearch"><!--<span id="searchResultsHintjqxCustomers" style="color:red;"></span>-->
      </div>
	  <div class="tableData tableNeView" style="overflow:visible">
        <div class="tableHading"> Supplier List </div>
        <div class="formTable manageMembers" id="jqxSuppliersLookup" style="width:100%"> </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">

searchByEnterKey('lookupsrc', 'supplierLookupSearch');
<!--EOF Supplier lookup list-->
$(document).ready(function() {		
	$("#intensity, #overtone").attr("disabled", "disabled");
	$("#intensity, #overtone").dropkick('refresh');
				
	$('#item_image').live('change', function(){ 
		$("#preview").html('');
		//$("#preview").html('<img src="loader.gif" alt="Uploading...."/>');
		$("#frm_diamond").ajaxForm({
			//target: '#preview',
			success: function(response){				
				if(response == 1){
					$('#preview').html('Invalid file format');
				}else if(response == 2){
					$('#preview').html('Unable to upload file');
				}else{
					$('#image').val(response);
					$('#item_image').val('');
					$('#preview').html('<img src="/inventory_images/'+response+'" height="98px" width="234px">');
				}
			}
		}).submit();
	});
	$('#item_invoice').live('change', function(){ 
		//$("#preview").html('<img src="loader.gif" alt="Uploading...."/>');
		$("#frm_diamond").ajaxForm({
			success: function(response){
				if(response == 1){
					$('#invoicePreview').html('Invalid file format');
				}else if(response == 2){
					$('#invoicePreview').html('Unable to upload file');
				}else{
					$('#invoice').val(response);
					$('#invoicePreview').html(response);
					$('#item_invoice').val('');
				}
			}
		}).submit();
	});
	$('#diamond_type').dropkick({
  		change: function () {
			var diamondTypeSelection = $("#diamond_type option[value="+$('#diamond_type option:selected').val()+"]").text();
			if(diamondTypeSelection == "Coloured"){
				$("#intensity, #overtone").removeAttr("disabled");
				$("#intensity, #overtone").dropkick('refresh');
				
				$("#color_type").show();
				$("#white_type").hide();
			} else {
				$('#intensity, #overtone').val(0);
				$("#intensity, #overtone").attr("disabled", "disabled");
				$("#intensity, #overtone").dropkick('refresh');
				
				$("#color_type").hide();
				$("#white_type").show();
			}
		}
	});
});
</script>