<!--BOF Supplier lookup list-->
<div class="lightBox" id="supplierlookup">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Supplier Lookup <a href="javascript:;" class="closePopup" title="Close">X</a></div>
    <div class="lightBoxContent fl width100p lookupPopup padB105">
      <div class="mainSearch">
        <input name="lookupsrc" id="lookupsrc" type="text" class="searchInput" placeholder="Search..">
        <input type="button" class="inputGo" value="Go!" onclick="suppliersLookup(<?php echo $this->recordsPerPage; ?>, '<?php echo $this->lookupSupplierId; ?>', '<?php echo $this->lookupSupplierName; ?>', $('#lookupsrc').val());" id="supplierLookupSearch">
      </div>
	  <div class="tableData tableNeView" style="overflow:visible">
        <div class="tableHading"> Supplier List </div>
        <div class="formTable manageMembers" id="jqxSuppliersLookup" style="width:100%"> </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
searchByEnterKey('lookupsrc', 'supplierLookupSearch');
</script>
<!--EOF Supplier lookup list-->