<div class="contentArea">
  <h2 class="cmnHeader">Users</h2>
  <a class="popupLink lightBoxClick" data-popup="userForm" href="javascript:;" onclick="openUserForm();">Add User</a><a class="popupLink lightBoxClick marL10" data-popup="masterPassword" href="javascript:;">Set Master Password</a>
  <div class="tableData tableNeView marB30" style="overflow:visible">
    <div class="tableHading" style="width:100%" id="bindAfterThis"> User List </div>
    <div class="formTable manageMembers" id="jqxUsers" style="width:100%"></div>    
  </div>
  <!--BOF Grid View Block-->
</div>

<!--BOF User Form -->
<div class="lightBox" id="userForm">
	<div class="lightBoxMid" style="width:890px">
		<div class="lightBoxTitle">User Form<a href="javascript:;" class="closePopup" title="Close">X</a></div>
		<div class="lightBoxContent fl width100p commonForm rowSpace" id="user_form_content"></div>
	</div>
</div>
<!--EOF User Form -->

<!--BOF Master Password Form -->
<div class="lightBox" id="masterPassword">
	<div class="lightBoxMid" style="width:500px">
		<div class="lightBoxTitle">Set Master Password<a href="javascript:;" class="closePopup" title="Close">X</a></div>
		<div class="lightBoxContent fl width100p commonForm rowSpace">
			<?php
			$masterPasswordForm->prepare();
			echo $this->form()->openTag($masterPasswordForm);
			?>
            <div class="alphaClmn width100p">
					<div class="formRow">
					  <label class="labelControll"><?php echo $this->masterPasswordForm->get('mp_password')->getLabel(); ?></label>
					  <div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->masterPasswordForm->get('mp_password')); ?></div></div>
					</div>
					<div class="formRow">
					  <label class="labelControll"><?php echo $this->masterPasswordForm->get('mp_confirm_password')->getLabel(); ?></label>
					  <div class="inputDiv"><div class="selectDrop width100p"><?php echo $this->formElement($this->masterPasswordForm->get('mp_confirm_password')); ?></div></div>
					</div>               
				  </div>
			
            
            <div class="formButtons tc fl width100p">
				<?php echo $this->formElement($this->masterPasswordForm->get('mp_save')); ?>
				<?php echo $this->formElement($this->masterPasswordForm->get('mp_cancel')); ?>
			</div>
            
            
			<?php echo $this->form()->closeTag(); ?>
		</div>
	</div>
</div>
<!--EOF Master Pasword Form -->

<script type="text/javascript">
$(document).ready(function(){
	geUsers(<?php echo $recordsPerPage; ?>);
});
</script>