<form name="frm_miscellaneous" id="frm_miscellaneous" method="post" enctype="multipart/form-data" action="/uploadfile">
  <div class="contentArea padLR0">
    <div class="pageLoader"></div>
    <div class="fl width100p contentINN">
      <div class="customerDetails">
        <label>Supplier Details</label>
        <div class="custonerInfo">
          <h2><?php echo $viewData['company_name']; ?></h2>
          <p>Ph: <?php echo $viewData['supplier_phone']; ?></p>
          <p>E: <a href="mailto:<?php echo $viewData['supplier_email']; ?>"><?php echo $viewData['supplier_email']; ?></a></p>
        </div>
      </div>
      <span class="deviderLine" ></span> </div>
    <div class="customerTabing fl width100p ctb">
      <ul>
        <li class="current"><a href="javascript:;">Miscellaneous Details</a></li>
      </ul>
      <div class="customTabbingInner">
        <!-- Lead Details -->
        <div class="customerTabingInfo" style="display:block">
          <div class="leadSummary QuoteMain">
          <a class="cmnBtn" id="saveMiscellaneousButton" href="javascript:;" onclick="updateMiscellaneous($('#frm_miscellaneous'));">Edit</a> &nbsp;
          <?php if ($canDelete) : ?>
          	<a class="cmnBtn redBtn" href="javascript:;" onclick="deleteMiscellaneous(<?php echo $viewData['id']; ?>);">Delete</a> &nbsp;
          <?php endif; ?>
            <!-- Lead Information-->
            <div class="tableData noOverflow width100p">
				<input id="miscellaneousRingId" type="hidden" value="<?php echo $viewData['id']; ?>" name="miscellaneousRingId">
				<input id="supplier_id" type="hidden" value="<?php echo $viewData['supplier_id']; ?>" name="supplier_id">
				<input id="invoice" type="hidden" value="<?php echo $viewData['invoice']; ?>" name="invoice">
              <div  class="tableHading width100p"> Miscellaneous Details <?php echo '- #'.$viewData['stock_code']; ?></div>
              <div class="fl width100p commonForm rowSpace suplierInfo editViewForm">
                  <div class="formRow">
                    <label class="labelControll">Title</label>
                    <div class="inputDiv displayHide">
                      <input type="text" class="inputTxt" id="title" name="title" value="<?php echo $viewData['title']; ?>" />
                    </div>
                    <p class="hiddenUnqValues" id="title_miscellaneous">
                      <?php 
					  echo $viewData['title']; ?>
                    </p>
                  </div>
                  <div class="formRow">
                    <label class="labelControll">CAD Stock Code</label>
                    <div class="inputDiv displayHide">
                      <input type="text" class="inputTxt" id="cad_code" name="cad_code" value="<?php echo $viewData['cad_code']; ?>" />
                    </div>
                    <p class="hiddenUnqValues" id="cad_code_miscellaneous">
                      <?php 
					  echo $viewData['cad_code']; ?>
                    </p>
                  </div>
				  <div class="formRow">
                    <label class="labelControll">Description</label>
                    <div class="inputDiv displayHide">
                      <textarea id="description" name="description" style="height:100px"><?php echo $viewData['description']; ?></textarea>
                    </div>
                    <p class="hiddenUnqValues" id="description_miscellaneous">
                      <?php 
					  echo $viewData['description']; ?>
                    </p>
                  </div>
				<div class="headSettings">
          <h2 class="cmnHeader">Supplier & Invoices</h2>
          <div class="alphaClmn">
            <div class="formRow">
              <label class="labelControll">Attach Invoice</label>
              <div class="inputDiv displayHide">
                <div class="inputfile"><span class="cmnBtn blueBtn marL0">Upload</span>
                  <input type="file" id="item_invoice" name="item_invoice">
                </div>
				<div class="uploadedInvoiceDisplay" id="invoicePreview"></div>
              </div>
			  <p class="hiddenUnqValues" id="invoice_diamond">
				<a href="/invoice/<?php echo $viewData['invoice']; ?>" id="invoice_link" target="_blank" <?php if(empty($viewData['invoice'])) echo 'style="display:none;"' ?>>Invoice</a>
              </p>
            </div>
            <div class="formRow">
              <label class="labelControll">Supplier Name</label>
              <div class="inputDiv displayHide"><input type="text" value="<?php echo $viewData['supplier_name']; ?>" class="inputTxt width60p" id="supplier_name" name="supplier_name" readonly="readonly"><a onclick="suppliersLookup(<?php echo $this->recordsPerPage; ?>, 'supplier_id', 'supplier_name');" data-popup="supplierlookup" class="cmnBtn blueBtn lightBoxClick" href="javascript:;">Lookup</a></div>
			  <p class="hiddenUnqValues" id="supplier_name_miscellaneous">
                      <?php 
					  echo $viewData['supplier_name']; ?>
                    </p>
            </div>
          </div>
          <div class="betaClmn">
            <div class="formRow">
              <label class="labelControll">Price</label>
              <div class="inputDiv displayHide"><input type="text" value="<?php echo $viewData['price']; ?>" class="inputTxt" id="price" name="price" data-numeric="yes" /></div>
			   <p class="hiddenUnqValues" id="price_miscellaneous">
                     <?php if($viewData['price'] > 0){ echo '$'.$viewData['price']; }?>
                    </p>
            </div>
          </div>
        </div>
              </div>
            </div>
            <div class="tableData noOverflow width100p">
              <div  class="tableHading width100p"> Consignment <a href="javascript:;" data-popup="consignItem" class="cmnBtn fr marT0 lightBoxClick" onclick="openConsignForm(<?php echo $viewData['id']; ?>, 'miscellaneous', 'edit');">Consign</a></div>
              <div class="fl width100p  suplierInfo">
                <div class="commonForm rowSpace addItemForm consignPopup consignPopupView">
                  <div class="headSettings padT0">
                    <h2 class="cmnHeader">Inventory Status</h2>
                    <div class="alphaClmn">
                      <div class="formRow">
                        <label class="labelControll">Inventory Status</label>
                        <p class="inputDiv" id="inventory_status_name_weddring"><?php echo $this->ConsignData['inventory_status_name']; ?></p>
                      </div>
                      <div class="formRow">
                        <label class="labelControll">Status Reason</label>
                        <div class="inputDiv" id="inventory_status_reason_weddring"><?php echo $this->ConsignData['inventory_status_reason']; ?></div>
                      </div>
                    </div>
                    <div class="betaClmn">
                      <div class="formRow">
                        <label class="labelControll">Inventory Type</label>
                        <div class="inputDiv" id="inventory_type_weddring"><?php echo $this->ConsignData['inventory_type']; ?></div>
                      </div>
                      <div class="formRow">
                        <label class="labelControll">Consignee Owner</label>
                        <div class="inputDiv" id="owner_name_weddring"><?php echo $this->ConsignData['owner_name']; ?></div>
                      </div>
                    </div>
                  </div>
                  <div class="headSettings">
                    <h2 class="cmnHeader">Inventory Reservation</h2>
                    <div class="alphaClmn">
                      <div class="formRow">
                        <label class="labelControll">Reserve Time</label>
                        <div class="inputDiv" id="reserve_time_weddring"><?php echo $this->ConsignData['reserve_time']; ?></div>
                      </div>
                    </div>
                    <div class="betaClmn">
                      <div class="formRow">
                        <label class="labelControll">Reserve Notes</label>
                        <div class="inputDiv" id="reserve_notes_weddring"><?php echo $this->ConsignData['reserve_notes']; ?></div>
                      </div>
                    </div>
                  </div>
                  <div class="headSettings">
                    <h2 class="cmnHeader">Item Location</h2>
                    <div class="alphaClmn">
                      <div class="formRow">
                        <label class="labelControll">Tracking Status</label>
                        <div class="inputDiv" id="inventory_tracking_status_weddring"><?php echo $this->ConsignData['inventory_tracking_status']; ?></div>
                      </div>
                      <div class="formRow">
                        <label class="labelControll">Tracking Reason</label>
                        <div class="inputDiv" id="inventory_tracking_reason_weddring"><?php echo $this->ConsignData['inventory_tracking_reason']; ?></div>
                      </div>
                    </div>
                    <div class="betaClmn">
                      <div class="formRow">
                        <label class="labelControll">Tracking ID</label>
                        <div class="inputDiv" id="tracking_id_weddring"><?php echo $this->ConsignData['tracking_id']; ?></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
<!--BOF Supplier lookup list-->
<?php echo $this->partial('inventory/index/supplierlookup.phtml', array('recordsPerPage' => $this->recordsPerPage, 'lookupSupplierId' => 'supplier_id', 'lookupSupplierName' => 'supplier_name')); ?>
<!--EOF Supplier lookup list-->
<!--BOF Add Consign Form -->
<div class="lightBox" id="consignItem">
	<div class="lightBoxMid" style="width:890px">
		<div class="lightBoxTitle">Consign Item	  -  Miscellaneous <a href="javascript:;" class="closePopup" title="Close">X</a></div>
		<div class="lightBoxContent fl width100p" id="consign_form_content">
		</div>
	</div>
</div>
<!--EOF Add Consign Form -->
<script type="text/javascript">
searchByEnterKey('lookupsrc', 'supplierLookupSearch');
$(document).ready(function() {
	$('#item_invoice').live('change', function(){ 
		//$("#preview").html('<img src="loader.gif" alt="Uploading...."/>');
		$("#frm_miscellaneous").ajaxForm({
			success: function(response){
				if(response){
					$('#invoicePreview').html(response);
					$('#invoice').val(response);
					$('#invoice_link').attr('href', '/invoice/'+response);
					$('#invoice_link').show();
					$('#item_invoice').val('');
				}
			}
		}).submit();
	});
});
</script>
