<ul>
  <li <?php echo $current == 'diamond' ? 'class="current"' : ''; ?>><a href="/inventory">Diamonds <!--<span id="inventoryDiamondsGlobal">0</span>--></a></li>
  <li <?php echo $current == 'weddingring' ? 'class="current"' : ''; ?>><a href="/inventory-weddingring">Wedd. Rings <!--<span id="inventoryWeddingringsGlobal1">0</span>--></a></li>
  <li <?php echo $current == 'engagementring' ? 'class="current"' : ''; ?>><a href="/inventory-engagementring">Eng. Rings <!--<span id="inventoryEngagementringsGlobal">0</span>--></a></li>
  <li <?php echo $current == 'earring' ? 'class="current"' : ''; ?>><a href="/inventory-earring">Earring <!--<span id="inventoryEarringsGlobal">0</span>--></a></li>
  <li <?php echo $current == 'pendant' ? 'class="current"' : ''; ?>><a href="/inventory-pendant">Pendants <!--<span id="inventoryPendantsGlobal">0</span>--></a></li>
  <li <?php echo $current == 'chain' ? 'class="current"' : ''; ?>><a href="/inventory-chain">Chains <!--<span id="inventoryChainsGlobal">0</span>--></a></li>
  <li <?php echo $current == 'miscellaneous' ? 'class="current"' : ''; ?>><a href="/inventory-miscellaneous">Miscellaneous <!--<span id="inventoryMiscellaneousGlobal">0</span>--></a></li>
  <li <?php echo $current == 'inventoryjobs' ? 'class="current"' : ''; ?>><a href="/inventoryjobs">Job Packets</a></a></li>
  <li <?php echo $current == 'weblinks' ? 'class="current"' : ''; ?>><a href="/websitelinks">External Web sites</a></li>
</ul>