<div class="tableData tableNeView marB30" style="overflow:visible">
<div class="tableHading" style="width:100%" id="bindAfterThis"> Order List </div>
<div class="formTable manageMembers" id="jqxOrders" style="width:100%"></div>  
</div>


<script type="text/javascript">
$(document).ready(function(){
	getOrders(<?php echo $recordsPerPage; ?>, null, <?php echo (isset($cust_id) && !empty($cust_id)) ? $cust_id : 0; ?>)
});
</script>