<div class="lightBox" id="oppCustomerDatalookup">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Customer Lookup <a href="javascript:;" class="closePopup" title="Close">X</a></div>
    <div class="lightBoxContent fl width100p lookupPopup padB105">
      <div class="mainSearch">
        <input name="lookupsrc" id="lookupOppCussrc" type="text" class="searchInput" placeholder="Search..">
        <input type="button" class="inputGo" value="Go!" onclick="oppCustomersLookup(<?php echo $this->recordsPerPage; ?>, '<?php echo $lookupCustomerId; ?>', '<?php echo $lookupCustomerName; ?>', $('#lookupOppCussrc').val());" id="customerLookupSearch"><span id="searchResultsHintjqxOppCus" style="color:red;"></span>
      </div>
      <div class="tableData tableDataView" style="overflow:visible">
        <div class="tableHading"> Customer List </div>
        <div class="formTable manageMembers" id="jqxOppCustomersLookup" style="width:100%"> </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
	searchByEnterKey('lookupOppCussrc', 'customerLookupSearch');
</script>