<div class="contentArea padLR0">
	<div class="fl width100p contentINN">
        <h2 class="cmnHeader">DE Collection</h2>
	</div>
	<div class="customerTabing fl width100p ctb">
        <?php echo $this->partial('inventory/index/tab.phtml', array('current' => 'weblinks')); ?>
        <div class="customTabbingInner">
			<div class="customerTabingInfo" style="display:block">
				<div class="QuoteMain">
					<div class="cb"></div>
					<div class="cb"></div>
					<div class="marB30 collectionInfo" style="width:100%">
						
						<?php /*?><div class="formTable manageMembers" id="jqxDianonds" style="width:100%">
							
						</div><?php */?>
                        <table border="0" cellpadding="8" cellspacing="0" width="100%" class="websiteLinks">
								<tr >
									<?php foreach($data['Rows'] as $key => $value): ?>
										<th height="38"><?php echo ucfirst($key); ?></th>
									<?php endforeach; ?>
								</tr>
								<tr >
                               
									<?php foreach($data['Rows'] as $key => $value): ?>
										<td height="48" valign="top">
											<?php foreach($value as $val): ?>
												<a <?php if($val['is_mail'] == 0){ ?>target="_blank" <?php }?> href="<?php if($val['is_mail']){ echo "mailto:".$val['website_link']; } else{ echo $val['website_link']; } ?>"><?php echo ucfirst($val['website_title']); ?></a> <br />
											<?php endforeach; ?>
										</td>
									<?php endforeach; ?>
								</tr>
							</table>
					</div>
				</div>
			</div>
        </div>
	</div>
</div>
