<div class="lightBox" id="opportunitylookup">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Opportunity Lookup <a href="javascript:;" class="closePopup" title="Close">X</a></div>
    <div class="lightBoxContent fl width100p lookupPopup">
      <div class="mainSearch">
        <input name="opp_lookupsrc" id="opp_lookupsrc" type="text" class="searchInput" placeholder="Search..">
        <input type="button" class="inputGo" value="Go!" onclick="getOpportunitiesLookup('jqxOpportunityLookup', <?php echo $this->recordsPerPage; ?>, <?php echo (isset($cust_id) && !empty($cust_id)) ? $cust_id : 0; ?>,  $('#opp_lookupsrc').val(), { 'filter_status' : ['Open', 'Closed Won'] });" id="customerLookupSearch"><span id="searchResultsHintjqxOpportunity" style="color:red;"></span>
      </div>
      <div class="tableData tableNeView" style="overflow:visible">
        <div class="tableHading"> Opportunity List </div>
        <div class="formTable manageMembers" id="jqxOpportunityLookup" style="width:100%"> </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
	getOpportunitiesLookup('jqxOpportunityLookup', <?php echo $recordsPerPage; ?>, <?php echo (isset($cust_id) && !empty($cust_id)) ? $cust_id : 0; ?>, '', { 'filter_status' : ['Open'] });
</script>