<!--BOF Reply Email Form -->
<?php
$replyEmailForm->prepare();
echo $this->form()->openTag($replyEmailForm);
echo $this->formElement($this->replyEmailForm->get('to_email'));
echo $this->formElement($this->replyEmailForm->get('to_name'));
?>

<div class="formRow">
	<label class="labelControll"><?php echo $emailData['to_name']; ?>&nbsp;&lt;<?php echo $emailData['to_email']; ?>&gt;</label>
</div>
<div class="formRow">
	<!--<label class="labelControll"><?php //echo $this->composeEmailForm->get('subject')->getLabel(); ?>*</label>-->
	<div class="inputDiv padL0"><?php echo $this->formElement($this->replyEmailForm->get('subject')); ?></div>
</div>
<div class="writeCommentBlock marB10">
	<?php echo $this->formElement($this->replyEmailForm->get('message')); ?>
	<div class="commentBottom">
	  <div class="attachfile">
		<?php echo $this->replyEmailForm->get('email_attachments')->getLabel(); ?>
		<?php echo $this->formElement($this->replyEmailForm->get('email_attachments')); ?>
		<?php echo $this->formElement($this->replyEmailForm->get('email_attachment_list')); ?>
	  </div>
	</div>
</div>
<div class="uploadedImages uploadImgNames" id="order_image_preview">
<?php if(count($attachments) > 0){
	foreach($attachments as $key => $data){ ?>
		<div class="upImg" id="order_galleryImg<?php echo $key; ?>"><img src="/order_attachment/<?php echo $data['attachment']; ?>" height="98px" width="98px"/><a class="closeImg" onclick="unlinkGalleryImage('order_attachment/<?php echo $data['attachment']; ?>','order_galleryImg<?php echo $key; ?>', 'frm_order', 'order_attachment', <?php echo $data['id']; ?>)" style="cursor:pointer">X</a></div>
<?php	}
} ?>
</div>
<div class="formRow">
	<label class="labelControll"><?php echo $this->replyEmailForm->get('copy_email')->getLabel(); ?>*</label>
	<div class="inputDiv datePickInput width150"><?php echo $this->formElement($this->replyEmailForm->get('copy_email')); ?></div>
</div>
<div class="formButtons tc fl width100p">
	<?php echo $this->formElement($this->replyEmailForm->get('send_email')); ?> <?php echo $this->formElement($this->replyEmailForm->get('email_cancel')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>
<!--EOF Reply Email Form -->