<div class="contentArea">
	<?php $this->headTitle('Forgot Password');	?>
	<div class="mainLoginForm">
		<div class="loginInner">
			<h1><?php echo $this->escapeHtml('Forgot Password'); ?></h1>
			<div class="loginFormFields">
				<form name="frm_forgotpass" id="frm_forgotpass" action="" method="post">
					<label>
						<span>Email</span>
						<input type="text" name="email" id="email" value="" />
					</label>
					<a style="margin-top:0" class="cmnBtn" href="javascript:;" onclick="sendResetPasswordUrl($('#frm_forgotpass'));">Submit</a>
				</form>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">

function validateResetPasswordUrl(){
	$('.errorText').remove();
	var errors = 0;
	if($('#email').val() == ''){
		$( '<p class="errorText">Please enter email id</p>' ).insertAfter( '#email' );
		errors++;
	}
	
	return errors;
}

function sendResetPasswordUrl(form){
	var errors = validateResetPasswordUrl();
	if(errors == 0){
		$.ajax({
			url: '/sendresetpassurl',
			type: 'POST',
			async: false,
			data: form.serialize(),
			success: function(response){
				if(response == 1){
					$('<p class="errorText">Password reset URL has been sent to your registered email id.</p>').insertAfter('#frm_forgotpass');
				}else{
					$('<p class="errorText">Please try again.</p>').insertAfter('#frm_forgotpass');
				}
			}
		});
	}
}
</script>