<?php
$this->HeadScript ()->appendFile ( '/js/jquery.min.1.11.0.js' );
$this->HeadScript ()->appendFile ( '/js/jquery-migrate-1.2.1.min.js' );
$this->HeadScript ()->appendFile ( '/js/jquery-ui.js' );
$this->HeadScript ()->appendFile ( '/js/jquery-ui-timepicker-addon.js' );
$this->HeadScript ()->appendFile ( '/js/dropkick.js' );
$this->HeadScript ()->appendFile ( '/js/jquery.maskedinput.min.js' );
$this->HeadScript ()->appendFile ( '/js/common.js' );
$this->HeadScript ()->appendFile ( '/js/leads.js' );
$this->HeadScript ()->appendFile ( '/js/opportunities.js' );
$this->HeadScript ()->appendFile ( '/js/notes.js' );
$this->HeadScript ()->appendFile ( '/js/tasks.js' );
$this->HeadScript ()->appendFile ( '/js/suppliers.js' );
$this->HeadScript ()->appendFile ( '/js/inventory.js' );
$this->HeadScript ()->appendFile ( '/js/weddingring.js' );
$this->HeadScript ()->appendFile ( '/js/engagementring.js' );
$this->HeadScript ()->appendFile ( '/js/earring.js' );
$this->HeadScript ()->appendFile ( '/js/pendant.js' );
$this->HeadScript ()->appendFile ( '/js/miscellaneous.js' );
$this->HeadScript ()->appendFile ( '/js/chain.js' );

$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxcore.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxdata.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxbuttons.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxscrollbar.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxlistbox.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxdropdownlist.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxmenu.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxgrid.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxgrid.pager.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxgrid.sort.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxgrid.filter.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxgrid.columnsresize.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxgrid.selection.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/jqxpanel.js' );
$this->HeadScript ()->appendFile ( '/js/jqwidgets/scripts/gettheme.js' );

$this->HeadScript ()->appendFile ( '/js/jquery.uploadify.min.js' );
$this->HeadScript ()->appendFile ( '/js/jsDatePick.jquery.full.1.3.js' );
$this->HeadScript ()->appendFile ( '/js/jquery.form.js' );
$this->HeadScript ()->appendFile ( '/js/jquery-ui-sliderAccess.js' );

$this->HeadScript ()->appendFile ( '/js/invoice.js' );
$this->HeadScript ()->appendFile ( '/js/order.js' );
$this->HeadScript ()->appendFile ( '/js/user.js' );

$this->HeadScript ()->appendFile ( '/js/colorpicker/colpick.js' );

echo $this->HeadScript ();