
<div class="contentArea padLR0">
      <div class="fl width100p contentINN">
        <h2 class="cmnHeader">Quotes & Invoices</h2>
      </div>
      <div class="customerTabing fl width100p ctb">
        <ul>
          <li class="current"><a href="javascript:;">Quotes</a></li>
          <li ><a href="javascript:;">Invoices <!--<span>84</span>--></a></li>
        </ul>
        <div class="customTabbingInner">
          <div class="customerTabingInfo" style="display:block">
            <div class="QuoteMain"> <a class="popupLink" href="/newquotes">Create New Quote</a>
              <div class="cb"></div>
              <div class="mainSearch marR10 marT15">

                      <input type="text" id="quote_search" placeholder="search.." class="searchInput" name="search" value="<?php echo $_GET['search']?>">
                <input type="button" onClick="javascript:getQuotes('quote-grid',10);" id="globalGridSearch" value="Go!" class="inputGo">
   
              </div>
              <div class="cb"></div>
				<!--<div class="tableData" style="width:100%">
					<div class="tableHading" style="100%">Quote</div>
					<div id="quote-grid"></div>
					<div id="gridpager"></div>				
				</div>-->
			  
				<div class="tableData tableNeView marB30" style="overflow:visible">
					<div class="tableHading" style="width:100%"> Quote </div>
					<div class="formTable manageMembers" id="quote-grid" style="width:100%"></div>  
				</div>
            </div>
          </div>
          <div class="customerTabingInfo">
          	<div class="QuoteMain"> <a class="popupLink lightBoxClick" href="/newinvoice"  data-popup="addItem">New Invoice</a>
              <div class="cb"></div>
              <div class="mainSearch marR10 marT15">
                
                      <input type="text" id="invoice_searchInput" placeholder="search.." class="searchInput" name="search">
                <input type="button" onClick="javascript:getInvoices('invoice-grid',10);" id="globalGridSearch" value="Go!" class="inputGo">
        
              </div>
              <div class="cb"></div>
				<!--<div class="tableData" style="width:100%">
					<div class="tableHading" style="100%">Invoices</div>				
					<div id="invoice-grid"></div>
				</div>-->
				<div class="tableData tableNeView marB30" style="overflow:visible">
					<div class="tableHading" style="width:100%"> Invoices </div>
					<div class="formTable manageMembers" id="invoice-grid" style="width:100%"></div>  
				</div>
            </div>
          </div>
        </div>
      </div>
    </div>
<script type="text/javascript">
    $(document).ready(function(){
        getQuotes("quote-grid",10)
        getInvoices("invoice-grid",10);
    })
    </script>