<div class="lightBox" id="customerlookup">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Customer Lookup <a href="javascript:;" class="closePopup" title="Close">X</a></div>
    <div class="lightBoxContent fl width100p lookupPopup padB105">
      <div class="mainSearch">
        <input name="lookupsrc" id="lookupsrc" type="text" class="searchInput" placeholder="Search..">
        <input type="button" class="inputGo" value="Go!" onclick="customersLookup(<?php echo $this->recordsPerPage; ?>, '<?php echo $lookupCustomerId; ?>', '<?php echo $lookupCustomerName; ?>', $('#lookupsrc').val());" id="customerLookupSearch"><span id="searchResultsHintjqxCustomers" style="color:red;"></span>
      </div>
	  <?php if($newCustomerForm){ ?>
	  <a class="popupLink lightBoxClick fr" data-popup="new_customer_form" href="javascript:;">New Customer</a>
	  <!--BOF new lead Form-->
		<?php echo $this->partial('customer/index/newcustomerform.phtml', array('form' => $this->newCustomerForm, 'identity' => $this->identity, 'recordsPerPage' => $this->recordsPerPage, 'disableLookup' => true)); ?>
	  <!--EOF new lead Form-->
	  <?php } ?>
      <div class="tableData tableNeView" style="overflow:visible">
        <div class="tableHading"> Customer List </div>
        <div class="formTable manageMembers" id="jqxCustomersLookup" style="width:100%"> </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
	searchByEnterKey('lookupsrc', 'customerLookupSearch');
</script>