<!--BOF Compose Email Form -->
<?php
$composeEmailForm->prepare();
echo $this->form()->openTag($composeEmailForm);
echo $this->formElement($this->composeEmailForm->get('milestone_id'));
echo $this->formElement($this->composeEmailForm->get('milestone_type_id'));
echo $this->formElement($this->composeEmailForm->get('step'));
?>

<div class="formRow">
	<label class="labelControll"><?php echo $milestoneData->supplier_name; ?>&nbsp;&lt;<?php echo $milestoneData->supplier_email; ?>&gt;</label>
</div>
<div class="formRow">
	<!--<label class="labelControll"><?php //echo $this->composeEmailForm->get('subject')->getLabel(); ?>*</label>-->
	<div class="inputDiv padL0"><?php echo $this->formElement($this->composeEmailForm->get('subject')); ?></div>
</div>
<div class="writeCommentBlock marB10">
	<?php echo $this->formElement($this->composeEmailForm->get('message')); ?>
	<div class="commentBottom">
	  <div class="attachfile">
		<?php echo $this->composeEmailForm->get('email_attachments')->getLabel(); ?>
		<?php echo $this->formElement($this->composeEmailForm->get('email_attachments')); ?>
		<?php echo $this->formElement($this->composeEmailForm->get('email_attachment_list')); ?>
	  </div>
	</div>
</div>
<div class="uploadedImages uploadImgNames">

</div>
<div class="formRow">
	<label class="labelControll"><?php echo $this->composeEmailForm->get('attachment_check')->getLabel(); ?>*</label>
	<div class="inputDiv datePickInput width150">
	<label class="labelCheck"><?php echo $this->formElement($this->composeEmailForm->get('attachment_check')); ?><i></i> </label></div>
</div>
<div class="formRow">
	<label class="labelControll"><?php echo $this->composeEmailForm->get('copy_email')->getLabel(); ?>*</label>
	<div class="inputDiv datePickInput width150"><label class="labelCheck"><?php echo $this->formElement($this->composeEmailForm->get('copy_email')); ?><i></i> </label></div>
</div>		
<div class="formButtons tc fl width100p">
	<?php echo $this->formElement($this->composeEmailForm->get('send_email')); ?> <?php echo $this->formElement($this->composeEmailForm->get('email_cancel')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>
<!--EOF Compose Email Form -->