<div class="lightBox" id="invoicelookup">
  <div class="lightBoxMid" style="width:970px">
    <div class="lightBoxTitle">Invoice Lookup <a href="javascript:;" class="closePopup" title="Close">X</a></div>
    <div class="lightBoxContent fl width100p lookupPopup">
     <!-- <div class="mainSearch">
        <input name="lookupsrc" id="lookupsrc" type="text" class="searchInput" placeholder="Search..">
        <input type="button" class="inputGo" value="Go!" onclick="getOpportunitiesLookup('jqxOpportunityLookup', <?php //echo $this->recordsPerPage; ?>, null,  $('#lookupsrc').val());" id="customerLookupSearch"><span id="searchResultsHintjqxOpportunity" style="color:red;"></span>
      </div>-->
      <div class="tableData tableNeView" style="overflow:visible">
        <div class="tableHading"> Invoice List </div>
        <div class="formTable manageMembers" id="jqxInvoiceLookup" style="width:100%"> </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
	//getInvoiceLookup();
</script>